### ISSUE TITLE
MOD09Q1 download issuue

### ISSUE THREAD

**Issue by SnehaMurmu** [lbusett/MODIStsp#100]
I am not able to download MOD09Q1 for the year 2016. I have tried http as well as ftp downloading options but in both the cases they are claiming that the server is down. Whereas I am able to access  https://e4ftl01.cr.usgs.gov/  without any problem. I don't have much experience in programming and started using R recently. So, please let me know if you need any other information. Thanks for your work on this package.

**Comment by ranghetti** [comment]
To help us to understand the reason of the problem, please follow these steps:
1) try to execute `MODIStsp(test = 5)` (it will ask your login information) and `MODIStsp(test = 6)`, and post the output;
2) post the JSON file with the parameters you are using.

Thanks,

**Comment by SnehaMurmu** [comment]
I have executed it with MODIStsp(test = 5) and MODIStsp(test = 6). The same output came in  both the cases attached below:
![capture1](https://user-images.githubusercontent.com/34543387/34092078-91789196-e3e7-11e7-90bb-c0aaad667791.JPG)

The JSON file parameter are as below:
![capture2](https://user-images.githubusercontent.com/34543387/34093240-30640f1a-e3ed-11e7-99c7-f63328807d7e.JPG)

**Comment by ranghetti** [comment]
I can confirm that MODIStsp(test = 5) and MODIStsp(test = 6) are running correctly on my PC (tested 10 minutes ago), so the problem is probably related to your internet settings. Please follow the recommentations given in the issue #74 to know it the problem is related to the presence of a firewall or a proxy.

**Comment by SnehaMurmu** [comment]
Its working now!!!
Thank you so much Ranghetti.
