### ISSUE TITLE
Function "MODIStsp_process_QA_bits" not found?

### ISSUE THREAD

**Issue by janeuhd** [lbusett/MODIStsp#103]
Hi, I've just installed MODIStsp for the first time and used it to download imagery and create time series. However, when attempting to use the function MODIStsp_process_QA_bits() to process VI_QAs it fails to find the function. I get error "Could not find function 'MODIStsp_process_QA_bits'". 
What am I missing? I use MODIStsp v 1.3.3.1 and GDAL 2.1.2 om Windows 10.
Thanks!

**Comment by lbusett** [comment]
Hi, 

     `MODIStsp_process_QA_bits` is an internal function which can not be called independently (I should probably remove "internals" from the help...). 

To create a time series of a given quality indicator, you should use the "standard" MODIStsp workflow: 

1) Open the GUI and select the product of interest, area and time frame; 
2) Click on "Select layers" and specify which Quality Indicator you are interested in; 
3) Start the processing (or save the Options File for later/no-interactive use)

(Have a look [HERE](http://lbusett.github.io/MODIStsp/articles/interactive_execution.html) for more detailed info)

Let us know if you have any problems / further needs for clarification. 

HTH, 

Lorenzo

**Comment by janeuhd** [comment]
I see. I have already made the QA time series, that is not the problem. What I was trying to do was to extract the bit values for bits 2-5 in order to identify the beste pixel based on VI_QA. Can this be done in MODIStsp?

**Comment by lbusett** [comment]
Yes. That can be done. 

When you select the layers to be processed, you should see a selector like this: 

![image](https://user-images.githubusercontent.com/4480397/34766029-6efa7f12-f5f3-11e7-866a-bc1e71bc3f80.png)

The "Quality Indicators" in the middle are derived by interpreting the QA bits of the Quality Layers contained in the original MODIS hdf file. For example, in this case (MOD13Q1), The "VI Quality" indicator is derived from bit 0 o th "VI quality indicators" original layer. "VI usefulness" from bits 2-5, 
Aerosol quantity from bits 6-7, etcetera. The "assignation" is based on MODIS products documentation, which you can always access form the Products webpage (linked in the GUI - though personally at the moment I am not able to access any lpdaac site...)

What product are you referring to, specifically?

**Comment by janeuhd** [comment]
Thanks for clearing this up. I did not realize that the QIs in the middle section were processed values from the original layers and only downloaded the original MODIS Rely and VI_QA layers. My mistake.
I use MOD13Q1 and MYD13Q1 mostly.

**Comment by lbusett** [comment]
No worries. It should probably better clarified in the GUI. What about if I change the "title" to something like: 

Quality Indicators (derived from bit-fields)

? Could it help?

**Comment by janeuhd** [comment]
Perfect for a novice like me!

**Comment by lbusett** [comment]
Ok. Will add that to the next version! Thanks for the feedback!
