### ISSUE TITLE
Save Options Not working

### ISSUE THREAD

**Issue by nishan3** [lbusett/MODIStsp#105]
"Save Options" is not working after I upgraded R and MODISStp versions (1.3.3.9).
R version 3.3.3, 64 bits, Windows 7.

Error: 
Error: lexical error: invalid char in json text.
                                       I:\mod11a
            (right here) ------^

**Comment by lbusett** [comment]
Hi,
 Sorry for the trouble. Could you please tell us which OS you are using and share your session info?

**Comment by nishan3** [comment]
I'm using Windows 7 64 bits- R version 3.3.3.
I'm trying to save options for downloading and processing  a subset of MOD11A1. 

Error: lexical error: invalid char in json text.
                           I:\mod11a
(right here) ------^

**Comment by lbusett** [comment]
Thanks. I'll have a look ASAP.

In the meantime, you could also try using the "official" version form cran, installing using

` install. packages("MODIStsp")`

**Comment by lbusett** [comment]
Hi , 
 I was not able to replicate the problem. Could you please take a screenshot of the GUI settings before clicking on "save options"? 

Also, could you send me the results of:

   `devtools::session_info() `

?

**Comment by nishan3** [comment]
After installing the official package it worked. 
Thanks for your prompt response.

**Comment by lbusett** [comment]
Glad you solved this. If possible, could you still provide a screenshot of the gui settings that were not working with the github version?

**Comment by nishan3** [comment]
Unfortunately, before I could capture the screenshot or get session info, it was solved.  But, the error is probably associated with "jsonlite",

Error: lexical error: invalid char in json text.
-------------------I:\mod11a
(right here) ------^
_______________________________________________________
Additionally, with the github version, there was a problem with "RGtk2" not being installed, which did not let MODIStsp GUI open (windows 7 64 bits, R 3.3.3). I also followed the instructions provided on github. But only after a fresh installation of RGtk2 separately, it was solved. 
install.packages("https://cran.r-project.org/bin/windows/contrib/3.3/RGtk2_2.20.31.zip", repos=NULL)

It's working perfectly now. Thanks for proving us this tool.

**Comment by lbusett** [comment]
Thanks, nonetheless. The problem concerning Rgtk2 is strange, since I have gwidgetsrgtk2 in imports, which should try to "force" installation of of Rgtk2... I'll have a look to see if I understand what's going on.
