### ISSUE TITLE
The stand-alone execution in Windows doesn't work

### ISSUE THREAD

**Issue by xiaocaoren** [lbusett/MODIStsp#106]
I want to run the programme without having to open R/RStudio in Windows 10. Therefore, according to the tutorial instruction in http://lbusett.github.io/MODIStsp/articles/standalone_execution.html#on-windows,  I set the stand-alone execution batch programme, but I didn't go through successfully. 
1) First of all, I already installed a launcher for MODIStsp, and the MODIStsp. bat located in directory "d:\Users\shq\Documents\R\win-library\3.4\MODIStsp\ExtData\Launcher\Batch", 
2) Then, I run "MODIStsp.bat" in command window, it works and prompt the GUI, which works the same as in the R/RStudio;
3) But, when I run "MODIStsp.bat -g -s ...", it prompted errors as following:
`d:\Users\shq\Documents\R\win-library\3.4\MODIStsp\ExtData\Launcher\Batch>MODIStsp.bat -g -s "d:\Users\shq\Documents\R\win-library\3.4\MODIStsp\Previous\MODIStsp_ProdOpts.RData"
MODIStsp
Warning message:
'MODIStsp'R3.4.3
Error in file.path(general_opts$out_folder, "Log") :
  'general_opts'`

And the corresponding  .json file (named "MODIStsp_Previous.json" in the same directory) is as follows:

```
{
 "sel_prod": "Vegetation_Indexes_16Days_1Km (M*D13A2)",
"sensor": "Both",
"prod_version": "6",
"start_date": "2017-07-01",
"end_date": "2017-12-31",
"bandsel": [      1,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0 ],
"indexes_bandsel": [      0,      0,      1,      1 ],
"quality_bandsel": [      0,      0,      0,      0,      0,      0,      0,      0,      0 ],
"start_x":     27,
"end_x":     28,
"start_y":      6,
"end_y":      6,
"user": "xiaocaoreniwhr",
"password": "Aniusun4379",
"use_aria": false,
"download_server": "http",
"download_range": "full",
"proj": "Latlon WGS84",
"user_proj4": "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
"out_res_sel": "Native",
"out_res": "native",
"full_ext": "Full Tiles Extent",
"resampling": "near",
"out_format": "GTiff",
"ts_format": "None",
"rts": "Yes",
"compress": {
 "None": "None" 
},
"nodata_change": "No",
"scale_val": "Yes",
"delete_hdf": "No",
"reprocess": "Yes",
"bbox": [ null, null, null, null ],
"out_folder": "E:\\ArcGIS\\DroughtMonitoring\\Dataset\\Hunan\\MOD",
"out_folder_mod": "E:\\ArcGIS\\DroughtMonitoring\\Dataset\\Hunan\\MOD",
"MODIStspVersion": "1.3.3.1",
"custom_indexes": [] 
}
```

Could anyone give me some suggestions?

**Comment by ranghetti** [comment]
Dear @xiaocaoren,
thank you for reporting this issue. Actually the Windows batch launcher had not been updated after a major changement made to MODIStsp options file (from RData object to JSON text file), so it was not possible to use it with current options files.
I made some changes in order to fix it: please reinstall MODIStsp from github and try again.
Notice that you have to use the command `d:\Users\shq\Documents\R\win-library\3.4\MODIStsp\ExtData\Launcher\Batch>MODIStsp.bat -g -s "d:\Users\shq\Documents\R\win-library\3.4\MODIStsp\Previous\MODIStsp_ProdOpts.json"`, with **`json`** extension.
