### ISSUE TITLE
No available data for year...

### ISSUE THREAD

**Issue by sjbehr** [lbusett/MODIStsp#107]
Hello,
I have downloaded the complete time series for the MOD11C3 product.
When I try to process it offline, I always get the "No available data for year: ..." error, no matter the processing period.
All the files are in the same folder with no subfolders.

**Comment by lbusett** [comment]
Hi, 

   just a check: are you following the instructions reported here: 

http://lbusett.github.io/MODIStsp/articles/faq.html#working-with-already-downloaded-hdf-files

?

**Comment by sjbehr** [comment]
Yes, I've followed the instructions. The time series starts in Feb/2000 and ends in Dec/2017.
In the GUI, the starting date is 2000-02-01 and the ending date is 2017-12-01, but nothing happens.
If I change the ending date to 2017-12-31, still nothing happens.
Here is the list of HDF files:
![list_files](https://user-images.githubusercontent.com/36040651/35689000-3b8af87c-0751-11e8-98b9-5353bf6fe893.jpg)
And here ir the parameters I use to process those files:
![list_parameters](https://user-images.githubusercontent.com/36040651/35689064-65563798-0751-11e8-9854-8e55918d0c71.jpg)
Thanks for your help.

**Comment by lbusett** [comment]
Thanks! I think I know what the problem is - will try to fix it ASAP. 

In the meantime, consider that if you already downloaded all the files, then processing with "http" or "ftp" will not require a new download if you specify the same folder for "Output Folder for Original HDF files.

**Comment by sjbehr** [comment]
Thanks! Now it works, changing "offline" for "http".

Best regards,
Santiago.-

**Comment by ranghetti** [comment]
Dear @sjbehr,
now this problem is fixed also in "offline" mode. You can try again after having updated the package from GitHub.
Best regards,
Luigi
