### ISSUE TITLE
Problems with GUI window

### ISSUE THREAD

**Issue by domras65** [lbusett/MODIStsp#109]
Dear friends, first of all, congratulation for your MODIStsp package. I installed successfully and worked with it a little bit in order to familiarize with the environment.  However, after an initial trial, using the GUI window, I am not able to reopen it. Each time I try, the machine sends me the following message:

> library(MODIStsp)
> MODIStsp()
Loading required package: gWidgetsRGtk2
Loading required package: RGtk2
Loading required package: gWidgets
Loading required package: cairoDevice
[Tue Feb 06 21:30:12 2018] Welcome to MODIStsp!We will now search for a valid GDAL installation - pleasewait! (this will happen only once)
GDAL version in use: 2.2.0

(rsession.exe:3688): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error en la l�nea 1, car�cter 100: Se cerr� el elemento �markup�, pero el elemento que est� abierto actualmente es �span�

(rsession.exe:3688): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error en la l�nea 1, car�cter 100: Se cerr� el elemento �markup�, pero el elemento que est� abierto actualmente es �span�
Error in if (proj == "longlat") { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: package ‘gWidgetsRGtk2’ was built under R version 3.4.3 
2: package ‘RGtk2’ was built under R version 3.4.3 
3: package ‘gWidgets’ was built under R version 3.4.3 

By the way, I am using a PC under windows 7.

Best regards

**Comment by lbusett** [comment]
Hi. Sorry for the trouble. Could you tell us if you are using the cran version or the github one?

**Comment by lbusett** [comment]
Hi. I was able to replicate this on the github version. It appears to happen if you specify a "user defined" projection. At next execution, the GUI fails to open. Could you confirm this?

I'll try to fix it ASAP. In the meantime, you could probably have it working again by deleting 
the "MODIStsp_Previous.json" file in the "ExtData/Previous" folder within the MODIStsp folder of your "R" library. If it does not work, you should probably reinstall the package.

**Comment by domras65** [comment]
Hi, and I confirm your guess, since I tried to download some staff using a
UTM projection suitable for the Iberian Peninsula (zone UTM30).

Again, wonderful tool.

Best regards

Domingo Rasilla
Department of Geography.
University of Cantabria
39005 Santander Spain



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-07 10:11 GMT+01:00 Lorenzo Busetto <notifications@github.com>:

**Comment by lbusett** [comment]
Should be fixed now. Install the latest github version for a working version.

**Comment by domras65** [comment]
Dear friend, thank you very much. I will do it.

Nevertheless, I have found another problem. When I try to visualize one of
the previous files downloaded by your tool, I am not able to do it. The
syntax used and the response are the following:

tif_file<-"MOD10_A2_MAX_SNW_2000_055.tif"
plot(tif_file)
Error in plot.window(...) : se necesitan valores finitos de 'ylim'
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf

I guess that the problem is related with the projection, and something is
missing, but I do not know what since I am not very familiar with
geographic projections; for Northern Spain, which is the area of interest,
the UTM zone is 30. So, could you take a look to both the tiff file and the
json file in order to help me?

The *.json parameters are the following (except password)
{
  "sel_prod": "Snow_Cov_8-Day_500m (M*D10_A2)",
  "sensor": "Terra",
  "prod_version": "6",
  "start_date": "2000-01-01",
  "end_date": "2018-02-07",
  "bandsel": [1, 0],
  "indexes_bandsel": 0,
  "quality_bandsel": [0, 0, 0, 0, 0, 0, 0, 0],
  "start_x": 17,
  "end_x": 17,
  "start_y": 4,
  "end_y": 4,
  "use_aria": false,
  "download_server": "http",
  "download_range": "full",
  "proj": "User Defined",
  "user_proj4": "+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs
+ellps=WGS84 +towgs84=0,0,0",
  "out_res_sel": "Native",
  "out_res": "native",
  "full_ext": "Resized",
  "resampling": "near",
  "out_format": "GTiff",
  "ts_format": "ENVI Meta Files",
  "rts": "No",
  "compress": "None",
  "nodata_change": "No",
  "scale_val": "No",
  "delete_hdf": "No",
  "reprocess": "No",
  "bbox": [300000, 4720000, 420000, 4830000],
  "out_folder": "C:\\Users\\Domingo\\Documents",
  "out_folder_mod": "C:\\Users\\Domingo\\Documents",
  "MODIStspVersion": "1.3.3.9000",
  "custom_indexes": []
}


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lbusett** [comment]
From the syntax you reported, It seems that you are not really opening the file, so you are trying to plot a string. 
 
You need at least something like: 

```
library(raster)
tif_file<-"MOD10_A2_MAX_SNW_2000_055.tif"
r <- raster(tif_file)
plot(r)
```

additionally, the string referencing to the file name needs to be a full path (unless the file is in your working dir).

**Comment by domras65** [comment]
Ok, thank you so much. A beginners mistake.

Best regards

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lbusett** [comment]
You're welcome.
