### ISSUE TITLE
Can't download Evapotranspiration

### ISSUE THREAD

**Issue by rodaguayo** [lbusett/MODIStsp#116]
I can not find the option to download the MOD16A2 product in ecosystem variables, although it appears here: http://lbusett.github.io/MODIStsp/articles/Products_list.html

**Comment by lbusett** [comment]
Hi, 

  MOD16A2 is currently available only on the "github" version. We are planning a new CRAN release soon, but in the meantime you could install the latest devel version using: 

    library(devtools)
    install_github("lbusett/MODIStsp", ref = "ropensci_review")

Lorenzo
