### ISSUE TITLE
Problem Accessing Processed Time Series

### ISSUE THREAD

**Issue by facetiousmuggle** [lbusett/MODIStsp#118]
I'm relatively new to R, and I am trying to access the processed time series from R. I'm working with MODIS vegetation indices. For the output folders I have separate ones for the HDF files and the Time Series (which has subfolders for each layer of interest). 

However, the only files in the time series folder are .tiff images for each date. Maybe the reason I can't progress to part 7 of the manual is because there is no virtual time series files and RasterStack RData objects stored with the naming convention of "ProdCode"_"Layer"_"StartDOY"_"StartYear_"EndDOY"_"EndYear_"suffix".ext" as mentioned in 6.2 of the manual. I don't know where that would have been stored if it was even created in the first place.

If that isn't the problem, then I am having trouble with the "in_virtual_file" and "indata" commands of step 7 of the manual. I keep getting a return message of  "probable reason 'No such file or directory'".

Please help,

A Frustrated Grad Student

**Comment by lbusett** [comment]
Hi. Sorry you are having trouble. One quick question:  are you using the CRAN or the github version?

**Comment by facetiousmuggle** [comment]
I believe I installed MODIStsp from CRAN using the install.packages("MODIStsp") command.

**Comment by lbusett** [comment]
OK . I suggest you to try to install the latest github version using: 

    install.packages("devtools")
    library(devtools)
    install_github("lbusett/MODIStsp")

When specifying your processing options in the GUI, select the kind of virtual time series files you wish to have from the GUI:

![image](https://user-images.githubusercontent.com/4480397/37642090-367f8880-2c1c-11e8-8b98-46aa53faa5b1.png)

Your time series files will be saved in the "time_series" subfolder of the main ouput folder, as described here: 

http://lbusett.github.io/MODIStsp/articles/output.html

Let me know if you still have problems.

**Comment by facetiousmuggle** [comment]
Before you had responded, I reran a download with a smaller timeframe and it did create a "time_series" subfolder. So I decided to give my version a second chance with the full timeframe. However, there were a few timeouts when downloading the sequence and after the last date was downloaded, I received this message in R:

[Tue Mar 20 13:07:03 2018] Creating Virtual Files and rts time series for layer NDVI
Error in system(cmd, intern = TRUE) : 
  'CreateProcess' failed to run 'C:\PROGRA~1\QGIS2~1.18\bin\GDALBU~1.EXE -separate  -srcnodata "-3000" -vrtnodata "-3000" "C:\Users\facetiousmuggle\Desktop\MODIS\MODIStsp\MODIS_VI_Time_Series/VI_16Days_250m_v6/Time_Series/GDAL/Terra/NDVI/MOD13Q1_NDVI_161_2000_241_2017_GDAL.vrt" "C:\Users\facetiousmuggle\Desktop\MODIS\MODIStsp\MODIS_VI_Time_Series/VI_16Days_250m_v6/NDVI/MOD13Q1_NDVI_2000_161.tif" "C:\Users\facetiousmuggle\Desktop\MODIS\MODIStsp\MODIS_VI_Time_Series/VI_16Days_250m_v6/NDVI/MOD13Q1_N

My guess is that the timeouts prevented the creation of the final raster stack. Do you still suggest I download the latest version from github, or do you suggest that I work with smaller timeframes?

**Comment by lbusett** [comment]
hi. 

  yes, I still suggest you to try and use the new version. I fear your problems may be due to sokme issues with paths in windiws which should have been solved on the latest version

**Comment by facetiousmuggle** [comment]
Even with the newer version, the last thing R says is: 

[Wed Mar 21 04:20:57 2018] Creating Virtual Files and R time series for layer NDVI
Error in system(cmd, intern = TRUE) : 
  'CreateProcess' failed to run 'C:\PROGRA~1\QGIS2~1.18\bin\GDALBU~1.EXE -separate  -srcnodata "-3000" -vrtnodata "-3000" "C:\Users\facetiousmuggle\Desktop\MODIS\MODIStsp\MODIS_VI_Time_Series/VI_16Days_250m_v6/Time_Series/GDAL/Terra/NDVI/MOD13Q1_NDVI_161_2000_241_2017_GDAL.vrt" "C:\Users\facetiousmuggle\Desktop\MODIS\MODIStsp\MODIS_VI_Time_Series/VI_16Days_250m_v6/NDVI/MOD13Q1_NDVI_2000_161.tif" "C:\Users\facetiousmuggle\Desktop\MODIS\MODIStsp\MODIS_VI_Time_Series/VI_16Days_250m_v6/NDVI/MOD13Q1_N

This time I did an offline download since I have all the HDFs downloaded for my time series and wanted to avoid possible timeouts. I may try doing it a year at a time and see if that helps.

**Comment by lbusett** [comment]
I doubt it is a problem of "length" of the series. To me, it seems more of a gdal path problem.  could you please try running
 
   MODIStsp(test = 4) 

and post the results ?

**Comment by facetiousmuggle** [comment]
Doing the test run, there was no error when creating the virtual files and time series. Here are the results from the test run:

![modistsp](https://user-images.githubusercontent.com/37280285/37750028-13b6825e-2d48-11e8-8db9-6d47691b6d10.jpg)

Running it year to year actually produced the .RData time series files. However, now I'm in the predicament of having to do the same commands 748 times (17 years x 4 layers x 11 shapefiles). Is there a way to work with multiple .RData, or multiple layer, or multiple shapefiles at the same time?

**Comment by lbusett** [comment]
That's strange..... 

    I'll ask for an additional test: Can you try to redo the processing with ONLY  the "R rasterStacks" option selected in the "time series format" selector? You can just re-run your analysis keeping the same output folders: download and processing will be skipped for already existing data, and only the time series creation part should run, so that should be quick.

**Comment by facetiousmuggle** [comment]
So I have all of my NDVI/EVI layers in two time series 2000-2009 and 2009-2017; however, I can't run the analysis for my MODIS LAI layer (even with an offline download). 

I'm now getting this error message:
![lai_problem](https://user-images.githubusercontent.com/37280285/37797625-969fd15e-2dd7-11e8-982c-93a37eddedf3.jpg)

**Comment by lbusett** [comment]
Ok, so we have a different problem. Could you please:

   1) try doing the same with "http" download 

AND

Save your options file from the GUI and send it to me ?

**Comment by facetiousmuggle** [comment]
I decided to come to campus to see if it was just my computer. On campus, I don't have any files downloaded so I planned on doing a small run to get the .HDF file (49th day of 2016) that I was missing from my 17 year timeframe. I used the "http" download and the same error occurred.

![csub_run](https://user-images.githubusercontent.com/37280285/37799130-ffe24968-2ddb-11e8-9d02-f5722135070f.jpg)

**Comment by lbusett** [comment]
One quick info: did you load the processing options from a JSON file you previously saved?

**Comment by facetiousmuggle** [comment]
Not on the computer on campus. I can't remember about my home computer.

**Comment by lbusett** [comment]
Ok. I think that something "bad" happened while updating the package - the "previous options" are not correctly read. 

Try this: 

     MODIStsp_reset_options()

answer "1"

then, quit and restart "R" and run MODIStsp() again. Insert your options manually and see what happens.

**Comment by facetiousmuggle** [comment]
This is the message that comes after pressing 1, but not yet restarting R.

[1] FALSE
Warning message:
In file.remove(prevopts_file) :
  cannot remove file '', reason 'No such file or directory'

**Comment by facetiousmuggle** [comment]
Then when I restart MODIStsp it asks the question of whether I should save the .json file from the last successful run. Asking me to authorize 1 for yes or 2 for no.

**Comment by lbusett** [comment]
Ok, what happens if you press "1", now? 

Also, May you have a look in your "R" win library folder, and look if you find a file named "MODIStsp_Previous.json" in folder "MODIStsp/ExtData/Previous/". If so, can you send it to me?

**Comment by facetiousmuggle** [comment]
Still the same error.

**Comment by facetiousmuggle** [comment]
There is a MODIStsp_Previous.json in the mentioned folder. How would I go about sending the file to you?

**Comment by lbusett** [comment]
Drag and drop here. After you send it to me , try deleting that file and run again.

**Comment by facetiousmuggle** [comment]
It's saying that .json files can't be supported when I try dragging it.

**Comment by lbusett** [comment]
ah, ok. Then just open it in a text editor, and cut and paste the content here.

**Comment by facetiousmuggle** [comment]
{
  "sel_prod": "Surf_Ref_8Days_500m (M*D09A1)",
  "sensor": "Terra",
  "prod_version": "6",
  "start_date": "2018-01-01",
  "end_date": "2018-03-22",
  "bandsel": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "indexes_bandsel": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "quality_bandsel": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "start_x": 18,
  "end_x": 18,
  "start_y": 4,
  "end_y": 4,
  "user": "",
  "password": "",
  "use_aria": false,
  "download_server": "http",
  "download_range": "full",
  "proj": "Native",
  "output_proj4": "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs",
  "out_res_sel": "Native",
  "out_res": "",
  "full_ext": "Select MODIS Tiles",
  "resampling": "near",
  "out_format": "GTiff",
  "ts_format": "rasterStack",
  "compress": "None",
  "nodata_change": "No",
  "scale_val": "No",
  "delete_hdf": "No",
  "reprocess": "No",
  "bbox": ["", "", "", ""],
  "out_folder": "$tempdir",
  "out_folder_mod": "$tempdir",
  "MODIStspVersion": "1.3.3.9000",
  "custom_indexes": []
}

**Comment by lbusett** [comment]
The file is ok. The GUI should therefore open correctly...

could you please run (on a fresh R session):  

    library(MODIStsp)
    devtools::session_info()

and paste here the results?

**Comment by facetiousmuggle** [comment]
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2018-03-22                  

Packages ----------------------------------------------------------------------
 package     * version    date       source                           
 base        * 3.4.4      2018-03-15 local                            
 bitops        1.0-6      2013-08-17 CRAN (R 3.4.1)                   
 codetools     0.2-15     2016-10-05 CRAN (R 3.4.4)                   
 compiler      3.4.4      2018-03-15 local                            
 data.table    1.10.4-3   2017-10-27 CRAN (R 3.4.4)                   
 datasets    * 3.4.4      2018-03-15 local                            
 devtools      1.13.5     2018-02-18 CRAN (R 3.4.3)                   
 digest        0.6.15     2018-01-28 CRAN (R 3.4.3)                   
 foreach       1.4.4      2017-12-12 CRAN (R 3.4.4)                   
 gdalUtils     2.0.1.7    2015-10-10 CRAN (R 3.4.4)                   
 graphics    * 3.4.4      2018-03-15 local                            
 grDevices   * 3.4.4      2018-03-15 local                            
 grid          3.4.4      2018-03-15 local                            
 gWidgets      0.0-54     2014-08-28 CRAN (R 3.4.4)                   
 httr          1.3.1      2017-08-20 CRAN (R 3.4.4)                   
 iterators     1.0.9      2017-12-12 CRAN (R 3.4.3)                   
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.4)                   
 lattice       0.20-35    2017-03-25 CRAN (R 3.4.4)                   
 magrittr      1.5        2014-11-22 CRAN (R 3.4.4)                   
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.4)                   
 methods     * 3.4.4      2018-03-15 local                            
 MODIStsp    * 1.3.3.9000 2018-03-22 Github (lbusett/MODIStsp@7926c16)
 pacman        0.4.6      2017-05-14 CRAN (R 3.4.4)                   
 parallel      3.4.4      2018-03-15 local                            
 R.methodsS3   1.7.1      2016-02-16 CRAN (R 3.4.1)                   
 R.oo          1.21.0     2016-11-01 CRAN (R 3.4.1)                   
 R.utils       2.6.0      2017-11-05 CRAN (R 3.4.4)                   
 R6            2.2.2      2017-06-17 CRAN (R 3.4.4)                   
 raster        2.6-7      2017-11-13 CRAN (R 3.4.4)                   
 Rcpp          0.12.16    2018-03-13 CRAN (R 3.4.4)                   
 rgdal         1.2-18     2018-03-17 CRAN (R 3.4.4)                   
 sp            1.2-7      2018-01-19 CRAN (R 3.4.4)                   
 stats       * 3.4.4      2018-03-15 local                            
 stringi       1.1.7      2018-03-12 CRAN (R 3.4.4)                   
 stringr       1.3.0      2018-02-19 CRAN (R 3.4.4)                   
 tools         3.4.4      2018-03-15 local                            
 utils       * 3.4.4      2018-03-15 local                            
 withr         2.1.2      2018-03-15 CRAN (R 3.4.4)                   
 xml2          1.2.0      2018-01-24 CRAN (R 3.4.4)                   
 xts           0.10-2     2018-03-14 CRAN (R 3.4.4)                   
 zoo           1.8-1      2018-01-08 CRAN (R 3.4.4)

**Comment by lbusett** [comment]
Ok. last two things:     

    library(gWidgetsRGtk2)
    devtools::session_info()

and send me results again. 

However, since the MODIStsp installation seems "corrupted" somehow, I'd suggest you to: 

1) Exit R, 
2) DELETE folder "MODIStsp" in your R win library
3) reinstall MODIStsp from github

BTW: Did you ever cloned the repo to your machine?m

**Comment by facetiousmuggle** [comment]
Before redownloading:

Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2018-03-22                  

Packages ----------------------------------------------------------------------
 package       * version date       source        
 base          * 3.4.4   2018-03-15 local         
 cairoDevice   * 2.24    2017-01-06 CRAN (R 3.4.1)
 compiler        3.4.4   2018-03-15 local         
 datasets      * 3.4.4   2018-03-15 local         
 devtools        1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest          0.6.15  2018-01-28 CRAN (R 3.4.3)
 graphics      * 3.4.4   2018-03-15 local         
 grDevices     * 3.4.4   2018-03-15 local         
 gWidgets      * 0.0-54  2014-08-28 CRAN (R 3.4.4)
 gWidgetsRGtk2 * 0.0-86  2018-03-01 CRAN (R 3.4.4)
 memoise         1.1.0   2017-04-21 CRAN (R 3.4.4)
 methods       * 3.4.4   2018-03-15 local         
 RGtk2         * 2.20.34 2018-01-25 CRAN (R 3.4.3)
 stats         * 3.4.4   2018-03-15 local         
 utils         * 3.4.4   2018-03-15 local         
 withr           2.1.2   2018-03-15 CRAN (R 3.4.4)

**Comment by facetiousmuggle** [comment]
I deleted the MODIStsp file from my library. When redownloading, it asks, 

[Thu Mar 22 15:33:06 2018] Welcome to MODIStsp!We will now search for a valid GDAL installation - pleasewait! (this will happen only once)
GDAL version in use: 2.2.3
MODIStsp would like to save a "MODIStsp_Previous.json" file 
containing information about its last successfull run in the folder 
`.../your-r-library/MODIStsp/ExtData/.` 

 Do you authorize this? 

1: Yes - "MODIStsp_Previous.json" will be saved permanently and updated after
after each successfull run of the tool. You will not see this message anymore.

2: No - Previous options will be written to `tempdir` and will be lost when you
exit `R`. You will see this message at each `MODIStsp` execution.

Should I press 1 or 2?

**Comment by facetiousmuggle** [comment]
Same error as before.

**Comment by facetiousmuggle** [comment]
Choice (1/2): 1
[1] "C:\\Users\\abaumgardner\\Desktop\\MODIS_LAI_Time_Series"
[1] "C:\\Users\\abaumgardner\\Desktop\\MODIS_LAI_HDF"
Error in if (general_opts$download_server == "ftp" & unique(ftp) == "Not Available") { : 
  argument is of length zero

**Comment by lbusett** [comment]
I really do not understand what's happening... It is taking some previous options from somewhere, but where??? Did you update "R" recently  ? are there multiple sub folders (i.e., multiple "versions") in your "R" win library folder?

**Comment by facetiousmuggle** [comment]
I updated to 3.4.4 on the computer I'm currently using and my one at home. This one has two versions of R; however, on this computer MODIStsp wouldn't even install on the old version.

**Comment by lbusett** [comment]
ok. Can yuo check if on the "3.4.X" (with "X" not equal 4) library folder you have a "MODIStsp" entry?

**Comment by facetiousmuggle** [comment]
In the other version (2.15), there is no MODIStsp entry; however there is a folder for gWidgets, gWidgetsRGtk2, installr, and RGtk2

**Comment by lbusett** [comment]
no, it should not matter. I really do not understand where the "wrong" previous options are coming from. 

Last thing, and then I have to leave you. What do you get if you run:

    ls()

before calling MODIStsp()?

**Comment by facetiousmuggle** [comment]
character(0)

Unless I'm doing something wrong. That is before and after doing library(MODIStsp)

**Comment by lbusett** [comment]
no, that is correct. I was wondering if there was something saved in your environment. 
I am out of ideas, right now. I'll see tomorrow if updating to 3.4.4 gives me trouble, but I doubt it. 

Really last thing: can you make a file search in your machine for "MODIStsp_previous.json" and see if it is found in different folders?

**Comment by lbusett** [comment]
Hi, 

    the problem with LAI products should now be fixed (I was looking in a completely wrong direction, before...). Please try removing the package with 

    remove.packages("MODIStsp")

, then reinstall from github and see if it works.
