### ISSUE TITLE
Problem related to evapotranspiration

### ISSUE THREAD

**Issue by rodaguayo** [lbusett/MODIStsp#120]
Hi,

the library works excellent, but the only thing is that you can not get the file list of the MOD16A3 product, so I had to download it manually and then process it. I'm using the Github version.

Rodrigo

**Comment by lbusett** [comment]
HI, 

   thanks for reporting this. I'll look into this. Could you please save your pricessing options from the GUI and send it to me ?

**Comment by lbusett** [comment]
Hi, 

   I had a look, and the http folder corresponding to MOD16A3 is currently empty: 

https://e4ftl01.cr.usgs.gov/MOLT/MOD16A3.006/

I do not know the reason for this. Where did you manage to download the data instead?

**Comment by lbusett** [comment]
Wait, digging a bit more I found this: 

https://lpdaac.usgs.gov/about/news_archive/modis_yearly_net_evapotranspiration_and_net_primary_production_version_6_products

so, this is not a MODIStsp problem, but a NASA issue. Apparently, however, you should not use those data until further notice. 

Closing now.
