### ISSUE TITLE
error in downloading and processing MODIS NDVI

### ISSUE THREAD

**Issue by bipin79** [lbusett/MODIStsp#121]
Dear author of MODIStsp,

I am trying to bulk download and process MODIS time series NDVI using the MODIStsp package in R (accessed from CRAN) but approached with some errors.  I tried my best to resolve it but could not  figure out properly . So, I am kindly asking your for your help. The errors message has been attached with this email. 

Looking forward for your help

Sincerely yours 

Bipin 
[MODIStsp_error.docx](https://github.com/lbusett/MODIStsp/files/1850650/MODIStsp_error.docx)

**Comment by lbusett** [comment]
Dear Bipin, 

  sorry you're having trouble. As a first step, I would try to install the latest MODIStsp version from github using:

    library(devtools)
    install_github("lbusett/MODIStsp")

If it still does not work, please contact us again, providing if possible also the MODIStsp options you are using (you can save them as a JSON file using the "Save" button in the GUI) .

**Comment by bipin79** [comment]
Dear Lorenzo,
Thank you very much. 
It is working well after the installation MODIStsp packager from github. Thank you once again. 
regards
Bipin

**Comment by lbusett** [comment]
Glad you solved this. We will soon release the new version on CRAN.

**Comment by bipin79** [comment]
Do not understand, why the following error is happening. "Timeout was reached: FTP response timeout". Could you please suggest to get rid of it.
 
un Apr 01 11:24:59 2018] [Sun Apr 01 11:24:59 2018] 4 files for date: 2011.05.01 were successfully downloaded!
[Sun Apr 01 11:25:03 2018] Processing and Reprojecting Terra NDVI files for date: 2011_05_01
[Sun Apr 01 11:25:13 2018] Processing and Reprojecting Terra VI_QA files for date: 2011_05_01
[Sun Apr 01 11:25:18 2018] Computing QA_qual for date: 2011_05_01
[Sun Apr 01 11:25:29 2018] Downloading Terra Files for date: 2011_06_01 : 1 of:  4
  |============================================================================================================| 100%
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached: FTP response timeout
In addition: Warning messages:
1: In if (general_opts$download_server == "ftp" & unique(ftp) == "Not Available") { :
  the condition has length > 1 and only the first element will be used
2: In if (general_opts$download_server == "http" & unique(http) ==  :
  the condition has length > 1 and only the first element will be used
[Sun Apr 01 11:58:41 2018] Download Error - Retrying...
  |============================================================================================================| 100%
[Sun Apr 01 12:28:48 2018] Downloading Terra Files for date: 2011_06_01 : 2 of:  4
  |============================================================================================================| 100%
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached: FTP response timeout
[Sun Apr 01 13:01:40 2018] Download Error - Retrying...
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached: Connection time-out
[Sun Apr 01 13:01:53 2018] Download Error - Retrying...

**Comment by bipin79** [comment]
I successfully processed MOD13A3 data of my study area.  Thank you Lorenzo, for the amazing package (MODIStsp).  It worked perfectly.

**Comment by lbusett** [comment]
Hi, 

    that kind of problems is usually due to temporary downtimes of the NASA servers. Usually, trying again after some hours solves the issue.
