### ISSUE TITLE
Can't link to NASA sever

### ISSUE THREAD

**Issue by hgbzzw** [lbusett/MODIStsp#124]
[Tue Apr 24 17:22:31 2018] Retrieving list of files from NASA server
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9485 milliseconds with 105296 bytes received
Trying to reach http server - attempt 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9781 milliseconds with 329468 bytes received
Trying to reach http server - attempt 2
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9781 milliseconds with 217382 bytes received
Trying to reach http server - attempt 3
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9797 milliseconds with 345481 bytes received
Trying to reach http server - attempt 4
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9797 milliseconds with 337477 bytes received
Trying to reach http server - attempt 5
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9781 milliseconds with 345481 bytes received
Trying to reach http server - attempt 6
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9532 milliseconds with 169348 bytes received
Trying to reach http server - attempt 7
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9782 milliseconds with 321459 bytes received
Trying to reach http server - attempt 8
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9782 milliseconds with 265416 bytes received
Trying to reach http server - attempt 9
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9813 milliseconds with 345481 bytes received
Trying to reach http server - attempt 10
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9781 milliseconds with 345481 bytes received
Trying to reach http server - attempt 11
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9782 milliseconds with 289438 bytes received
Trying to reach http server - attempt 12
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9532 milliseconds with 201372 bytes received
Trying to reach http server - attempt 13
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9781 milliseconds with 225391 bytes received
Trying to reach http server - attempt 14
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9782 milliseconds with 225391 bytes received
Trying to reach http server - attempt 15
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 9797 milliseconds with 233395 bytes received

**Comment by lbusett** [comment]
Hi, 

    could you tell us if you are using http or ftp download, and also which product and version you are trying to access?

**Comment by hgbzzw** [comment]
![setting](https://user-images.githubusercontent.com/26102249/39281957-f090c4e8-4939-11e8-9215-1311f2fca077.png)

**Comment by hgbzzw** [comment]
Thanks a lot! now it can work very well!
