### ISSUE TITLE
Can I download MCD18A1 and MCD18A2 datasets?

### ISSUE THREAD

**Issue by hgbzzw** [lbusett/MODIStsp#126]
Hi
I  am willing to use the MCD18A1(short-name for the Level-3 Terra and Aqua combined MODIS-derived surface radiation product in the shortwave spectrum)  and MCD18A2(short-name for the Level-3 Terra and Aqua combined MODIS-derived photosynthetically active radiation (PAR) product in the shortwave spectrum), but it could not be found in your available lists, Would you mind adding them to your work? 
Thanks a lot!

**Comment by lbusett** [comment]
@hgbzzw

Hi, sorry for the late reply. I was out of office for a few days. The product you mention is not currently available (is it a new one). I'll try to add it ASAP. Will keep you posted.

**Comment by lbusett** [comment]
Hi, 

    MCD18A1 and MCD18A2 should now work on the github version. Only problem is that it is not possible to create rasterStack time series startin from single-date data, due to the fact that PAR and RAD are stored as multiband layers in the original HDF files. 

If you may test the functionality, we'd be happy to have your feedback.

**Comment by lbusett** [comment]
Closed due to lack of activity. Feel free to reopen if needed.

**Comment by supernitt** [comment]
@lbusett I downloaded the MCD18A2 but it told me that no product available at the selected date (3-hour PAR in 2015). When I try another date like 2018 and 2019, it works. What should I do for this issue? Thanks.
