### ISSUE TITLE
MODIStsp PROBLEMS after update to 1.3.4

### ISSUE THREAD

**Issue by lbusett** [lbusett/MODIStsp#132]
Hi Lorenzo,
 I'm a modistsp user. I recently updated the program and started having some problems.
When I want to process data of some product, eg MOD13Q1. A) It does not let me select clipping files. Eg KML or SHP. B) I cancel the processing on the first date. Also install the mapedit and shiny libraries.
Before the update it worked perfectly.

The message that appears to me is the following.

> [Mon Jun 18 09:32:51 2018] [Mon Jun 18 09:32:50 2018] 1 files for date: 2015.08.13 were successfully downloaded!
> [Mon Jun 18 09:33:19 2018] Processing Terra NDVI files for date: 2015_08_13
> Error in seq.default (y [1], and [length (y)]):
>   'from' can not be NA, NaN or infinite
> In addition: Warning messages:
> 1: In if (general_opts $ download_server == "http" & unique (http) ==:
>   The condition has length> 1 and only the first element will be used
> 2: In if (general_opts $ download_server == "http" & unique (http) ==:
>   The condition has length> 1 and only the first element will be used
> 3: running command '"C: \ Program Files \ QGIS 3.0 \ bin \ gdalinfo.exe" "HDF4_EOS: EOS_GRID:" C: \ MODIS R / MOD13Q1.A2015225.h12v11.006.2015305194943.hdf ": MODIS_Grid_16DAY_250m_500m_VI: 250m 16 days NDVI "'had status 1
> > library ("MODIStsp", lib.loc = "~ / R / win-library / 3.3")
> > library ("mapedit", lib.loc = "~ / R / win-library / 3.3")
> Error in loadNamespace (i, c (lib.loc, .libPaths ()), versionCheck = vI [[i]]):
>   there is no package called 'shiny'
> In addition: Warning message:
> package 'mapedit' was built under R version 3.3.3
> Error: package or namespace load failed for 'mapedit'

Emanuel From Argentina

**Comment by lbusett** [comment]
Hi Emanuel, 

    sorry for the trouble. Would it be possible for you to save your caurrent processing options from the GUI and send them to us? 

Also, I noticed that you are still using "R" 3.3, and that "mapedit" seems not to be properly installed. 

Would it be possible for you to upgrade to a newer "R" version, and update your packages to current versions? 


Lorenzo

**Comment by emanuellunatoledo** [comment]
Hi Lorenzo.
I do not understand what this is: "Would it be possible for you to save your processing options in progress from the GUI and send them to us?"
I will detail how is the processing I am doing. With the previous version of MODIS-TSP I have not had any problems.
I use the Windows 7 operating system. The first thing I did was to update the Rstudio program. Then update all the packages.
Install GDAL and install MODIS-TSP again. Then install Mapedit.
 
> install.packages("mapedit")
Installing package into ‘C:/Users/adminlocal/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘Rcpp’, ‘units’, ‘httpuv’, ‘later’, ‘leaflet’, ‘miniUI’, ‘sf’, ‘shiny’


  There are binary versions available but the source versions are later:
         binary  source needs_compilation
Rcpp    0.12.16 0.12.17              TRUE
units     0.5-1   0.6-0             FALSE
httpuv    1.4.1 1.4.4.1              TRUE
later     0.7.1   0.7.3              TRUE
leaflet   2.0.0   2.0.1             FALSE
miniUI    0.1.1 0.1.1.1             FALSE
sf        0.6-1   0.6-3              TRUE
shiny     1.0.5   1.1.0             FALSE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/Rcpp_0.12.16.zip'
Content type 'application/zip' length 4358189 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/httpuv_1.4.1.zip'
Content type 'application/zip' length 1118480 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/later_0.7.1.zip'
Content type 'application/zip' length 605749 bytes (591 KB)
downloaded 591 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/sf_0.6-1.zip'
Content type 'application/zip' length 39296219 bytes (37.5 MB)
downloaded 37.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/mapedit_0.4.1.zip'
Content type 'application/zip' length 71025 bytes (69 KB)
downloaded 69 KB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘httpuv’ successfully unpacked and MD5 sums checked
package ‘later’ successfully unpacked and MD5 sums checked
package ‘sf’ successfully unpacked and MD5 sums checked
package ‘mapedit’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\adminlocal\AppData\Local\Temp\Rtmpu6vNBq\downloaded_packages
installing the source packages ‘units’, ‘leaflet’, ‘miniUI’, ‘shiny’

trying URL 'https://cran.rstudio.com/src/contrib/units_0.6-0.tar.gz'
Content type 'application/x-gzip' length 912393 bytes (891 KB)
downloaded 891 KB

trying URL 'https://cran.rstudio.com/src/contrib/leaflet_2.0.1.tar.gz'
Content type 'application/x-gzip' length 2059787 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/src/contrib/miniUI_0.1.1.1.tar.gz'
Content type 'application/x-gzip' length 97958 bytes (95 KB)
downloaded 95 KB

trying URL 'https://cran.rstudio.com/src/contrib/shiny_1.1.0.tar.gz'
Content type 'application/x-gzip' length 2350156 bytes (2.2 MB)
downloaded 2.2 MB

* installing *source* package 'units' ...
** package 'units' successfully unpacked and MD5 sums checked

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
Warning: comando ejecutado 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="units.dll" OBJECTS="RcppExports.o io.o udunits.o"' tiene estatus 127
ERROR: compilation failed for package 'units'
* removing 'C:/Users/adminlocal/Documents/R/win-library/3.3/units'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\adminlocal\Documents\R\win-library\3.3" C:\Users\ADMINL~1\AppData\Local\Temp\Rtmpu6vNBq/downloaded_packages/units_0.6-0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status
* installing *source* package 'leaflet' ...
** package 'leaflet' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'shiny'
ERROR: lazy loading failed for package 'leaflet'
* removing 'C:/Users/adminlocal/Documents/R/win-library/3.3/leaflet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\adminlocal\Documents\R\win-library\3.3" C:\Users\ADMINL~1\AppData\Local\Temp\Rtmpu6vNBq/downloaded_packages/leaflet_2.0.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘leaflet’ had non-zero exit status
* installing *source* package 'shiny' ...
** package 'shiny' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.4.1 is being loaded, but >= 1.4.3 is required
ERROR: lazy loading failed for package 'shiny'
* removing 'C:/Users/adminlocal/Documents/R/win-library/3.3/shiny'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\adminlocal\Documents\R\win-library\3.3" C:\Users\ADMINL~1\AppData\Local\Temp\Rtmpu6vNBq/downloaded_packages/shiny_1.1.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status
ERROR: dependency 'shiny' is not available for package 'miniUI'
* removing 'C:/Users/adminlocal/Documents/R/win-library/3.3/miniUI'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\adminlocal\Documents\R\win-library\3.3" C:\Users\ADMINL~1\AppData\Local\Temp\Rtmpu6vNBq/downloaded_packages/miniUI_0.1.1.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘miniUI’ had non-zero exit status



Run the program: Here I indicate what is the product and what is the layer of interest. It does not let me select a cut (neither with .shp nor with .kml). 

Error in bbox_from_file(file_path = choice, crs_out = out_proj_crs) : 
  C:\Users\adminlocal\Documents\2018\potreros (1)\perimetro.kmlis not recognised by GDAL or OGR as a valid spatialfile. Please check your inputs. Aborting!



Therefore I select MODIS Tiles H12V11, it does not perform the processing either.
This is the output that shows me in the R console
> MODIStsp::MODIStsp()
Loading required package: gWidgetsRGtk2
Loading required package: RGtk2
Loading required package: gWidgets
Loading required package: cairoDevice
[Thu Jun 21 09:27:33 2018] Welcome to MODIStsp!We will now search for a valid GDAL installation - pleasewait! (this will happen only once)
GDAL version in use: 2.0.1
The option file in use (C:/Users/adminlocal/Documents/R/win-library/3.3/MODIStsp/ExtData/Previous/MODIStsp_Previous.json) was created with an old MODIStsp version (1.3.3.9000)
 Although this should still work, please consider reopening the JSON file from the GUI
 and resaving it.
[Thu Jun 21 09:46:21 2018] MODIStsp --> Starting processing
[Thu Jun 21 09:46:22 2018] Accessing http server at:  http://e4ftl01.cr.usgs.gov/MOLT/MOD13Q1.006/
[Thu Jun 21 09:46:26 2018] Retrieving list of available ` Terra ` Files for Year 2015
[Thu Jun 21 09:46:34 2018] HDF File: MOD13Q1.A2015225.h12v11.006.2015305194943.hdf already exists on your system. Skipping download!
[Thu Jun 21 09:46:34 2018] [Thu Jun 21 09:46:34 2018] 1 files for date: 2015.08.13 were successfully downloaded!
[Thu Jun 21 09:47:17 2018] Processing Terra NDVI files for date: 2015_08_13
Error in seq.default(y[1], y[length(y)]) : 
  'from' cannot be NA, NaN or infinite
In addition: Warning messages:
1: package ‘gWidgetsRGtk2’ was built under R version 3.3.3 
2: In if (general_opts$download_server == "http" & unique(http) ==  :
  the condition has length > 1 and only the first element will be used
3: running command '"C:\Program Files\QGIS 3.0\bin\gdalinfo.exe" "HDF4_EOS:EOS_GRID:"C:\MODIS R\cerrillo/MOD13Q1.A2015225.h12v11.006.2015305194943.hdf":MODIS_Grid_16DAY_250m_500m_VI:250m 16 days NDVI"' had status 1

**Comment by lbusett** [comment]
Hi Emanuel, 

>    I do not understand what this is: "Would it be possible for you to save your processing options in progress from the GUI and send them to us?"

This means opening MODIStsp GUI, selecting the processing options (product, dates, etcetera) as you would do for a normal run and then, instead of clicking "start processing", clicking "save options" on the bottom right. 

If all goes well, you will be asked to specify an output file (.json) where the processing options will be saved. Please open that file in a text editor, and paste its contents here (or send me the file directly).

**Comment by lbusett** [comment]
Also, it could be useful if you could send me the shp/kml file you are trying to use for subsetting (by mail is also ok)

**Comment by emanuellunatoledo** [comment]
Hi Lorenzo, 
This is information from json file

{
  "sel_prod": "Vegetation Indexes_16Days_250m (M*D13Q1)",
  "sensor": "Both",
  "prod_version": "6",
  "start_date": "2015-01-01",
  "end_date": "2018-06-01",
  "bandsel": [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "indexes_bandsel": [0, 0, 0, 0],
  "quality_bandsel": [0, 0, 0, 0, 0, 0, 0, 0, 0],
  "start_x": 12,
  "end_x": 12,
  "start_y": 11,
  "end_y": 11,
  "user": "emanuellunatoledo",
  "password": "Oxford48319888",
  "use_aria": false,
  "download_server": "http",
  "download_range": "full",
  "proj": "Native",
  "output_proj4": "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs",
  "out_res_sel": "Native",
  "out_res": "Native",
  "full_ext": "Select MODIS Tiles",
  "resampling": "near",
  "out_format": "GTiff",
  "ts_format": ["R rasterStack", "ENVI Meta", "GDAL vrt"],
  "compress": "None",
  "nodata_change": "Yes",
  "scale_val": "Yes",
  "delete_hdf": "No",
  "reprocess": "Yes",
  "bbox": ["NA", "NA", "NA", "NA"],
  "out_folder": "C:\\MODIS R\\cerrillo",
  "out_folder_mod": "C:\\MODIS R\\cerrillo",
  "MODIStspVersion": "1.3.3.9000",
  "custom_indexes": []
}

**Comment by emanuellunatoledo** [comment]
Hi Lorenzo, Attached are the clipping vector files.
 Emanuel


 

    El jueves, 21 de junio de 2018 10:37:55 ART, Lorenzo Busetto <notifications@github.com> escribió:  
 
 
Also, it could be useful if you could send me the shp/kml file you are trying to use for subsetting (by mail is also ok)

**Comment by lbusett** [comment]
Hi, 

    as a first step, could you please try to use an output folder without "spaces" and see what happens? 
(e.g., C:/MODIS_R)

Lorenzo

**Comment by lbusett** [comment]
also, could you try running: 
   
    library(MODIStsp)
    MODIStsp(test = 5)

and see if they complete correctly?

**Comment by emanuellunatoledo** [comment]
Hi Lorenzo,
I corrected the name of the folder (without space) and the problem persisted.
So I uninstalled Rstudio and also R and reinstalled it. Then I had a problem with a file called libatk-1.0-0.dll that would not let me run modistsp.
I solved everything and now I was able to execute the program normally. I guess the problem must have been outdated bookstore. I do not know.

**Comment by lbusett** [comment]
Yes, you probably ended up in some "limbo" related to package version issues. Glad you solved this!

Lorenzo
