### ISSUE TITLE
"Surf_Temp_8Days_1Km (M*D11A2)" download platform option 'Aqua' doesn't seem to work

### ISSUE THREAD

**Issue by haipochan** [lbusett/MODIStsp#133]
Hi, Thank you very much for the powerful MODIStsp. I am happy to find your tool timely when I am in desperate need of big amount of MODIS data.

There are 3 options of MODIS data source platform: Both, Terra, Aqua.

However, when selecting option 'Aqua', the error appears in RStudio console as below.
---------------------
[1] "D:\\Atlas\\Documents\\Mayon.json"
Error in if (general_opts$download_server == "http" & http["Aqua"] ==  : 
  missing value where TRUE/FALSE needed
---------------------
When selecting 'Both' or 'Terra', the result is OK.
---------------------
[1] "D:\\Atlas\\Documents\\Mayon.json"
TRUE
---------------------

**Comment by lbusett** [comment]
Hi. Thanks for reporting. Could you tell us which MODIS product you are analysing?

**Comment by lbusett** [comment]
Hi. Thanks for reporting this. I will check ASAP.

**Comment by lbusett** [comment]
Hi. 

   this should now be fixed. Could you try installing the last github version to test it? 

Lorenzo

**Comment by haipochan** [comment]
This works fine now. Thank you Lorenzo for the fast remedy. :-)
