### ISSUE TITLE
MOD44B v6

### ISSUE THREAD

**Issue by marcusspiegel** [lbusett/MODIStsp#144]
Hello,
I am trying to download MOD44B, but the GUI is only allowing me to select version 5.1. I have installed the latest version of MODIStsp from Github, which describes the most recent news as having updated MOD44B, but the GUI does not seem to reflect this. Is there a quick fix? Thanks for a great package otherwise.

**Comment by lbusett** [comment]
@marcusspiegel

Hi. Could you try first to remove the package using

``` r

remove.packages("MODIStsp")
```

, resrart the r session and then install again from github?

**Comment by marcusspiegel** [comment]
I have reinstalled from github, but no progress. As far as I can tell, the products options from "/ExtData/Previous/MODIStsp_ProdOpts.RData" still need to be updated

**Comment by lbusett** [comment]
You are probably right. I updated the xml with product characteristics, but maybe did not push an updated corresponding prodopts file. I'll keep you posted.

**Comment by marcusspiegel** [comment]
Yes reinstalled and now it works. Thanks!
