### ISSUE TITLE
Optimise the download functions

### ISSUE THREAD

**Issue by ggranga** [lbusett/MODIStsp#39]
- explore the use of curl library instead of RCurl;
- search - if possible - for a way to retrieve the list of available tiles where modis servers are down; if not possible, add an option to skip this step and only process local hdf files

**Comment by lbusett** [comment]
Partially solved changed in 1.2.2: download now using "GET" function in "httr" package, which also allows easy authentication and cookies setting.

**Comment by ggranga** [comment]
First point: partially solved + issue 50;
Second point: added an "offline" mode to process only local HDF files (now in devel)
