### ISSUE TITLE
Allow downloading v6 products

### ISSUE THREAD

**Issue by ggranga** [lbusett/MODIStsp#40]
- Add v6 products in the XML file
- Add an option for the download

**Comment by ggranga** [comment]
All v6 products have been inplemented in devel branch. Test them before merging in master.

**Comment by pilong** [comment]
Thanks! Stable version (in 64 bit R 3.3.1, Win7 x64 )works well, but get stucked at try to use the devel version to process MODIS collection 006. Here is the error information I got:
install_github("lbusett/MODIStsp", ref="devel")
Downloading GitHub repo lbusett/MODIStsp@devel
from URL https://api.github.com/repos/lbusett/MODIStsp/zipball/devel
Installing MODIStsp
"C:/Users/SHI138/Documents/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/SHI138/AppData/Local/Temp/RtmpQ5U5jA/devtools1d789de3c89/lbusett-MODIStsp-c02213b"  \
  --library="C:/Users/SHI138/Documents/R/R-3.3.1/library" --install-tests 

* installing *source* package 'MODIStsp' ...
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'MODIStsp'
* removing 'C:/Users/SHI138/Documents/R/R-3.3.1/library/MODIStsp'
* restoring previous 'C:/Users/SHI138/Documents/R/R-3.3.1/library/MODIStsp'
Error: Command failed (1)

**Comment by ggranga** [comment]
Unfortunately I cannot reproduce the error on two Windows machines. I made the configuration.win file executable: could you please test if the error is still present? Thank you

**Comment by lbusett** [comment]
Closed on release of 1.3.0
