### ISSUE TITLE
Error in UseMethod("xmlAttrs", node) :    no applicable method for 'xmlAttrs' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by bmarcos** [lbusett/MODIStsp#51]
Does not launch. Instead gives the following output on first launch:

```
> MODIStsp()
Loading required namespace: gWidgetsRGtk2
Loading required package: gWidgetsRGtk2
Loading required package: RGtk2
Loading required package: gWidgets
Loading required package: cairoDevice
Scanning for GDAL installations...
Checking Sys.which...
GDAL version 2.1.0
GDAL version in use: 2.1.0 
Error in UseMethod("xmlAttrs", node) : 
  no applicable method for 'xmlAttrs' applied to an object of class "NULL"
> 
```

And just the following message from then on:

```
> MODIStsp()
GDAL version in use: 2.1.0 
Error in UseMethod("xmlAttrs", node) : 
  no applicable method for 'xmlAttrs' applied to an object of class "NULL"
> 
```

I have installed the latest (as of October 25th, 2016) devel version in two separate computers (one with Xubuntu Linux 16.04 64-bit, the other one with Windows Vista 64-bit), both with R 3.3.1. Used to work well before...

**Comment by ggranga** [comment]
Thank you for the warning, just fixed.

**Comment by bmarcos** [comment]
Hi,

Thank you very much! On Windows it is now working OK!

On Linux however, the same error appears, plus during installation it gives
the following outputs (note that it does install, however, some error
messages appear):

> install_github('lbusett/MODIStsp', ref = 'devel', force = TRUE)
> Downloading GitHub repo lbusett/MODIStsp@devel
> from URL https://api.github.com/repos/lbusett/MODIStsp/zipball/devel
> Installing MODIStsp
> '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore
> --quiet  \
>   CMD INSTALL
> '/tmp/RtmpkeC9TU/devtools2c8464171f3/lbusett-MODIStsp-bfddd1f'  \
>   --library='/home/bmarcos/R/x86_64-pc-linux-gnu-library/3.3'
> --install-tests
>
> * installing *source* package ‘MODIStsp’ ...
> Found pkg-config cflags and libs!
> Using PKG_CFLAGS=-pthread -I/usr/include/gtk-2.0
> -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/
> -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0
> -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12
> -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12
> -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0
> -I/usr/include/freetype2 -I/usr/include/glib-2.0
> -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
> Using PKG_LIBS=-lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0
> -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0
> -lfontconfig -lfreetype -lglib-2.0 -lcurl
>
> *./configure: 84: ./configure: cannot create src/Makevars: Directory
> nonexistent./configure: 87: ./configure: cannot create
> tools/option_table.txt: Directory nonexistent*
> ** R
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> * DONE (MODIStsp)
> >
>



*Bruno André Santos Marcos*
PhD student

InBIO - Research Network in Biodiversity and Evolutionary Biology,
Associate Laboratory
CIBIO - Research Center in Biodiversity and Genetic Resources
PRECOL - Predictive Ecology research group

Webpage: http://cibio.up.pt/people/details/bsmarcos
ResearchGate: http://www.researchgate.net/profile/Bruno_Marcos

<https://www.researchgate.net/profile/Cristiana_Vieira/>

2016-10-25 12:08 GMT+01:00 Luigi Ranghetti <notifications@github.com>:

**Comment by lbusett** [comment]
Hi, 

    the messages in Installation are not a problem - we are testing automatic checks on installation of required libraries. The error is strange... When did you install ? I'm asking because yesterday we "lost" the correction Luigi did for some time due to a commit error. Can you try again  ?

Lorenzo

**Comment by lbusett** [comment]
Also: sorry for the mess, but we are preparing to release the devel version with added functionality, and  while "adding" the different features we sometimes mess-up...

**Comment by bmarcos** [comment]
Oh, and also, when I try to set a user defined output projection in devel
version it gives the following error and I can't input the proj4 string:

Error in paste(...) : argument "msg" is missing, with no default



*Bruno André Santos Marcos*
PhD student

InBIO - Research Network in Biodiversity and Evolutionary Biology,
Associate Laboratory
CIBIO - Research Center in Biodiversity and Genetic Resources
PRECOL - Predictive Ecology research group

Webpage: http://cibio.up.pt/people/details/bsmarcos
ResearchGate: http://www.researchgate.net/profile/Bruno_Marcos

<https://www.researchgate.net/profile/Cristiana_Vieira/>

2016-10-26 15:39 GMT+01:00 Bruno Marcos <brunoasmarcos@gmail.com>:

**Comment by bmarcos** [comment]
Hi,

Development version is now working for me in both Windows and Linux! The
only thing that I noticed is not working at the moment is the 'add index'
window - it does not launch and it gives the following error message in the
console:

Error in load(general_opts$prodopts_file) : bad 'file' argument


Also, if I may make a suggestion, you could add some notes on the syntax to
use on a custom index, e.g. the correct names of the bands to be used in
order for it to work correctly (in my opinion, simply "b1, ..., b7" would
do, but "Red, NIR, ..., SWIR2" would work fine as well).

I'm ok with the mess, I just figured it would help if I gave some feedback,
in case you haven't noticed something wasn't working properly.

Thank you for this wonderful tool. I used to use some scripts that managed
to do everything the package does, but this speeds up the process for me,
as well as I think it facilitates a lot for people that are not as much
familiarized with MODIS as I am...

Cheers,



*Bruno André Santos Marcos*
PhD student

InBIO - Research Network in Biodiversity and Evolutionary Biology,
Associate Laboratory
CIBIO - Research Center in Biodiversity and Genetic Resources
PRECOL - Predictive Ecology research group

Webpage: http://cibio.up.pt/people/details/bsmarcos
ResearchGate: http://www.researchgate.net/profile/Bruno_Marcos

<https://www.researchgate.net/profile/Cristiana_Vieira/>

2016-10-26 11:27 GMT+01:00 Lorenzo Busetto <notifications@github.com>:

**Comment by lbusett** [comment]
Hi.  Thanks for the beta testing.  Ee recently switched to a different package for the gui,  and apparently it broke several things. 
The syntax for custom index shiuld be reported in the vignette,  but i agree it could be a good idea to put it also in the readme. 

Lorenzo

**Comment by ggranga** [comment]
Dear Bruno,
both the errors (custom projection and custom index) should be fixed now.
Thank you for signaling them; if you have other reports do not hexitate to open new separate issues to signal them.
