### ISSUE TITLE
Error in processing MOD13C2

### ISSUE THREAD

**Issue by pilong** [lbusett/MODIStsp#52]
R x64 3.3.1, Win7 x64, stable version of MODIStsp
other modis product work well,but for MOD13C2, each exported data folder (for exsample: VI_Monthly_005dg\b2_NIR) only hdr file was there(MOD13C2_b2_NIR_2000_032.hdr), no data file.
Here are the error message:

Scanning for GDAL installations...
Checking Sys.which...
Checking common locations...
GDAL version 2.1.2
GDAL version in use: 2.0.1 
[1] "E:\TS\MOD13C2\TS"
[1] "E:\TS\MOD13C2\HDF"
[1] "E:\TS\MOD13C2\World_2000-2008"
No encoding supplied: defaulting to UTF-8.
[Fri Oct 28 11:39:52 2016]Downloading Terra Files for date 2000_02_01 : 1  of  1

No encoding supplied: defaulting to UTF-8.
[Fri Oct 28 11:41:43 2016]1 files for date of 2000.02.01 were successfully downloaded!
[Fri Oct 28 11:41:43 2016] Processing Terra VI_QA files for date:  2000_02_01
[Fri Oct 28 11:41:48 2016] Processing Terra b1_Red files for date:  2000_02_01
[Fri Oct 28 11:41:52 2016] Processing Terra b2_NIR files for date:  2000_02_01
[Fri Oct 28 11:41:57 2016] Processing Terra Rely files for date:  2000_02_01
[Fri Oct 28 11:42:01 2016]Computing  Terra   GV  for date:  2000_02_01
Error in .local(.Object, ...) : 
  `E:\TS\MOD13C2\TS\VI_Monthly_005dg\b1_Red\MOD13C2_b1_Red_2000_032.dat' does not exist in the file system,
and is not recognised as a supported dataset name.

In addition: Warning messages:
1: In memory.limit(8000) : cannot decrease memory limit: ignored
2: running command '"C:\OSGeo4W64\bin\gdalbuildvrt.exe" -sd "3" -srcnodata "65535" -vrtnodata "65535" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9c6a8240e.vrt" "E:\TS\MOD13C2\HDF/MOD13C2.A2000032.005.2006272104028.hdf"' had status 1 
3: running command '"C:\OSGeo4W64\bin\gdal_translate.exe" -a_nodata "65535" -ot "UInt16" -of "ENVI" -a_srs "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9c6a8240e.vrt" "E:\TS\MOD13C2\TS/VI_Monthly_005dg/VI_QA/MOD13C2_VI_QA_2000_032.dat"' had status 1 
4: running command '"C:\OSGeo4W64\bin\gdalbuildvrt.exe" -sd "4" -srcnodata "-1000" -vrtnodata "32767" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9c173b48a6.vrt" "E:\TS\MOD13C2\HDF/MOD13C2.A2000032.005.2006272104028.hdf"' had status 1 
5: running command '"C:\OSGeo4W64\bin\gdal_translate.exe" -a_nodata "32767" -ot "Int16" -of "ENVI" -a_srs "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9c173b48a6.vrt" "E:\TS\MOD13C2\TS/VI_Monthly_005dg/b1_Red/MOD13C2_b1_Red_2000_032.dat"' had status 1 
6: running command '"C:\OSGeo4W64\bin\gdalbuildvrt.exe" -sd "5" -srcnodata "-1000" -vrtnodata "32767" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9c11783805.vrt" "E:\TS\MOD13C2\HDF/MOD13C2.A2000032.005.2006272104028.hdf"' had status 1 
7: running command '"C:\OSGeo4W64\bin\gdal_translate.exe" -a_nodata "32767" -ot "Int16" -of "ENVI" -a_srs "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9c11783805.vrt" "E:\TS\MOD13C2\TS/VI_Monthly_005dg/b2_NIR/MOD13C2_b2_NIR_2000_032.dat"' had status 1 
8: running command '"C:\OSGeo4W64\bin\gdalbuildvrt.exe" -sd "13" -srcnodata "-1" -vrtnodata "255" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9ce0c6d55.vrt" "E:\TS\MOD13C2\HDF/MOD13C2.A2000032.005.2006272104028.hdf"' had status 1 
9: running command '"C:\OSGeo4W64\bin\gdal_translate.exe" -a_nodata "255" -ot "Byte" -of "ENVI" -a_srs "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" "C:\Users\SHI138\AppData\Local\Temp\RtmpCaOGIO\file2e9ce0c6d55.vrt" "E:\TS\MOD13C2\TS/VI_Monthly_005dg/Rely/MOD13C2_Rely_2000_032.dat"' had status 1 
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)

**Comment by ggranga** [comment]
There was a check in the code searching for spatial resolution of data in the product metafiles, which are missing in MOD13C2. Now this check works in a different way, and the problem should be solved. But please test it, since my error log is quite different; if the error would still be present, please save a json configuration file and copy here its content.

**Comment by pilong** [comment]
Thanks!
R 3.3.2 x64, Win10 X64, MODIStsp v1.3.0.9000
Tried different products, Now both have a error:
> MODIStsp()
GDAL version in use: 2.0.1 
Error in custom_idx$indexes_bandnames : 
  $ operator is invalid for atomic vectors

**Comment by ggranga** [comment]
I cannot reproduce the error: try deleting both MODIStsp_Previous.json and MODIStsp_ProdOpts.RData (in subdirectory "Previous" of your installed MODIStsp directory) and re-run. If the error will still be present, please save a json configuration file and copy here its content (also in case of future errors).

**Comment by lbusett** [comment]
Hi. I apparently messed-up the custom index creation in the last commits. I'll solve it ASAP. 

Lorenzo

**Comment by lbusett** [comment]
This should be fixed now. To test, please:

1. remove current version of MODIStsp and of gWidgets, gWidgets2, gWidgetsRGtk2 and gWidgets2RGtk2 from your library;
2. Close and reopen RStudio (or whatever you use)
3. reinstall gWidgetsRGtk2 
4. reinstall MODIStsp devel. 

Let us know if it works !

**Comment by lbusett** [comment]
no. Still bugged.... sorry...

**Comment by lbusett** [comment]
Ok. Should be really fixed now by commit: https://github.com/lbusett/MODIStsp/commit/3fb1be2999960c5ac442fe8dbeb3438027664c45

**Comment by lbusett** [comment]
Hi. We updated yesterday to "stable" 1.3.0 release. Could you check if it solved your problems ? 

Lorenzo

**Comment by pilong** [comment]
Hi Lorenzo and ggranga,
I tried the new 1.3.0 stable version, the problems was solved, now the custom index I defined works pretty well!
Well done! Thanks!
Pilong

**Comment by lbusett** [comment]
you're welcome ! Thanks for beta-testing !
