### ISSUE TITLE
Allow multi-year download of only one part of the year

### ISSUE THREAD

**Issue by lbusett** [lbusett/MODIStsp#54]
At the moment, specifying start date 2005-03-01 and end date 2015-06-30 will process ALL images between the two dates, but sometimes it can be useful to download only one "season", but for multiple years.

Need to make so that the user can do "splitted" download, so that, for example, data BETWEEN 03-01 and 06-03 for MULTIPLE YEARS can be downloaded without downloading anything else

**Comment by ggranga** [comment]
Implemented in devel.
