### ISSUE TITLE
error on selecting user defined projection

### ISSUE THREAD

**Issue by bmarcos** [lbusett/MODIStsp#57]
While changing from 'Sinusoidal' to 'User defined', gives the following error, which prevents the user from inserting the proj4 string for the user defined projection:

`Error in paste(...) : argument "message" is missing, with no default`

Changing the proj4 string and bbox directly from the JSON file, and then loading it on the GUI, allows for the processing to run, but the message appears once more.

**Comment by lbusett** [comment]
Thanks for reporting. Will fix ASAP.

Lorenzo

**Comment by lbusett** [comment]
Should be fixed on commit https://github.com/lbusett/MODIStsp/commit/5ec15275f20042bfcc9227f5b97c69dea0132f05

Feel free to re-open if you still have problems !
