### ISSUE TITLE
Someting wrong with Processing MCD12Q1 

### ISSUE THREAD

**Issue by pilong** [lbusett/MODIStsp#58]
trying to process some MCD12Q1 LandCover data, but got wrong result.
R x64 3.3.2
MODIStsp v1.3.0
Got nothing output result but a hdr file "MCD12Q1_LC1_2013_001.hdr" and content is "data ignore value =  255 "

**Comment by lbusett** [comment]
Hi.  I'm currently on holiday.  I'll have a look after the 5th of January.

**Comment by lbusett** [comment]
This should be fixed on commit https://github.com/lbusett/MODIStsp/commit/17e007a41d039a4b5b31e7e160ea974151e8b86b

Feel free to re-open if needed.

(by the way: On MCD12Q1 be careful not to use any years after 2009)
