### ISSUE TITLE
vegetation index calculation from MCD43A4

### ISSUE THREAD

**Issue by geolinuxer** [lbusett/MODIStsp#59]
MODIStsp is very helpful tools to download and pre-process MODIS images, moreover, it also includes vegetation indices calculation. However, VI calculation from MCD43A4 (BRDF reflectance data) is still missing from the options. I hope the next version will facilitate this calculation. I thank you in advance for the effort of the developer(s).

**Comment by ggranga** [comment]
Spectral indices were added on products MCD43A4 (v5-v6), MCD43B4 (v5), MCD43C4 (v5-v6) with commit e92e2179cfae38c81240cc1beff806f763f8cf1a (both on master and devel); please inform us (reopening this issue) in case some errors would be still present.
