### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SOloo15** [lbusett/MODIStsp#63]
Hi 

I experience this error when i run the installation code

Error: Command failed (1)

Steve

**Comment by ggranga** [comment]
Dear SOloo15,
we need some more detail (OS, R version, code which you used to try to install, devtools version - if you used it -, detailed output) to reproduce an error so generic.

**Comment by CXlope** [comment]
Dear ggranga,
I was getting the following message at the end of the installation process described in the code : 

> installing
>  *source* package 'MODIStsp' ...
> ** R
> ** inst
> ** preparing package for lazy loading
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called 'foreach'
> ERROR: lazy loading failed for package 'MODIStsp'
> * removing 'C:/Program Files/R/R-3.3.2/library/MODIStsp'
> Erreur : Command failed (1)

- Windows 7 64-bit
- R version 3.3.2 64-bit
- GDAL 2.1.3 (OSgeo4W64 Installation)

When I successfully installed the package "foreach" that seems to be missing, the same error message kept appearing with new missing packages (Rcpp, R.utils, stringi, zoo) and after installing those, it just printed the errors with no more specifications.

I realized the automatic installation of GTK+ was installing the 32-bit version (and was not adding any path to the environment variable 'PATH'). 

I reinstalled R in the 32-bit version and manually added the path "C:/Program files/GTK+/bin" (where I previously copied the 32-bit GTK+ binaries) to the environment variable PATH. After installing the missing packages, which were again asked for, it happened to work just fine.

This site helped with the installation : https://www.stat.auckland.ac.nz/~kimihia/rgtk2

Thank you, and I help the feedback helps,
CXlope

**Comment by lbusett** [comment]
Hi, thanks for the report. 
The problem related to the incomplete installation of dependencies seems to be related to a bug in the CRAN version of `install_github`. 

For reference, see [**_Here_**](https://github.com/lbusett/MODIStsp/wiki#github-error) for a possible solution. 

Lorenzo
