### ISSUE TITLE
Pausing download and Processing(MODIStsp)

### ISSUE THREAD

**Issue by forester4ever** [lbusett/MODIStsp#66]
Hello all,
came across this package, quite nice one. Have installed it and is working now.
My question is, is there any function that allows for pausing and and resuming the download and processing?
I have looked through decription in the package and alos in the closed issues in this forum but did not find any clue.
I will appreciate if someone can point me in the right direction.
Thanks for you assistance.

**Comment by lbusett** [comment]
Hi,

   at the moment, pausing the processing is not possible, sorry.
As a possible workaround, consider that already downladed and processed dates are automatically skipped if you keep the same output folders. Therefore, if you "kill" rstudio at some point and then re-run the same processing, you will restart where you left. 

I know it's not an ideal solution, but at the moment we are not thinking of implementing a "pause" functionality.

Lorenzo

**Comment by forester4ever** [comment]
Thank you Lorenzo. I appreciate.

Augustine
