### ISSUE TITLE
MODISTsp Installation

### ISSUE THREAD

**Issue by effie-pav** [lbusett/MODIStsp#67]
Hi,
I am trying to install MODISTsp (Windows 7, R 3.3.3, GDAL 2.1.3) after loading gWidgetsRGtk2 and devtools as you describe. I'm getting the following error:
---------------------------------------------
> install_github("lbusett/MODIStsp")
Downloading GitHub repo lbusett/MODIStsp@master from URL https://api.github.com/repos/lbusett/MODIStsp/zipball/master
Installing MODIStsp
"D:/R-32~1.3/R-33~1.3/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/***/***/***/Temp/RtmpAZ4RWF/devtools119c2f747d1d/lbusett-MODIStsp-3e7e04b"  \
  --library="D:/R-3.2.3/R-3.3.3/library" --install-tests 

* installing *source* package 'MODIStsp' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
-----------------------
At this point I receive a pop-up window informing me that the program can't start because libatk-1.0-0.dll is missing. The pop-up window gets stuck and I need to kill the R session.
However: when this pop-up appered the first time, I did install GTK+. I did make sure the PATH variables (both system and user) were updated. I restarted both R and the system. I tried installing GTK+ manually to bypass the issue, but no improvement. 
Any advice? 
Thank you,
Effie

**Comment by lbusett** [comment]
Hi Effie, 
        
   can you please try this:

     1)  Remove packages "gWidgets", "gWidgetsRGtk2" and "RGtk2" using `remove.packages`
     2) Remove package `MODIStsp`

**Comment by effie-pav** [comment]
Hi Lorenzo,
thank you so much for the immediate response. The error message reads:
--------------------------------
> library("gWidgetsRGtk2", lib.loc="D:/R-3.2.3/R-3.3.3/library")
Loading required package: RGtk2
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'D:/R-3.2.3/R-3.3.3/library/RGtk2/libs/x64/RGtk2.dll':
  LoadLibrary failure:  The specified module could not be found.

trying URL 'http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip'
Content type 'application/zip' length 25830230 bytes (24.6 MB)
downloaded 24.6 MB

Learn more about GTK+ at http://www.gtk.org
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Loading required package: gWidgets
Loading required package: cairoDevice
Warning messages:
1: Failed to load RGtk2 dynamic library, attempting to install it. 
2: In dir.create(config_path, recursive = TRUE) :
  'D:\R-3.2.3\R-3.3.3\library\RGtk2\gtk\x64\etc\gtk-2.0' already exists
------------------------------------------
GTK+ indeed exists, and the path is updated.

**Comment by lbusett** [comment]
ok. What happens if you now close and reopen RStudio and try to load `gWidgetsRGtk` again ?

**Comment by effie-pav** [comment]
The packages are loading, but MODIStsp installation is interrupted at
*** arch -i386
With the message:
The procedure entry point deflateSetHeader could not be located in the dynamic link library zlib1.dll

The same happens when I load gWidgets2RGtk. I do close/reopen R, and the system as well.Do you think this has to do with the package and its dependencies, or with the architecture of the installation? (Would it help uninstalling and reinstalling R from scratch?)
Thank you again for the support..!

**Comment by lbusett** [comment]
ok... that's slightly different from what happens usually. 

Can you try to follow instructions reported here: 

https://www.stat.auckland.ac.nz/%7Ekimihia/rgtk2

?

**Comment by effie-pav** [comment]
Yes!, it worked very nicely. The page you referred to is very useful. The only thing not working was the link to the bundle. I downloaded the GTK+ bundle from http://www.tarnyko.net/dl/gtk.htm (apparently my system had issues with the GTK+ Windows Runtime Environment Installers).
To successfully install MODISTsp I also had to manually (re)install the following packages:
foreach,  Rcpp, R.utils, stringi, magrittr, and zoo.
Thank you again for the support, and for taking the effort and time to put this tool online-it is great, and much needed!

**Comment by lbusett** [comment]
Ok, glad that it worked !

By the way: the issue about having to manually install some packages is due to a bug in `install_github` that can usually be solved by installing the `github` version of `devtools`: 

On a fresh R session:

`devtools::install_github("hadley/devtools")`

Lorenzo
