### ISSUE TITLE
For Help

### ISSUE THREAD

**Issue by hgbzzw** [lbusett/MODIStsp#68]
How to mosaic different MODIS titles datas using MODIStsp?

**Comment by lbusett** [comment]
Hi, 

no need to do anything. Just set the tiles you want to process in the main GUI:

![immagine](https://cloud.githubusercontent.com/assets/4480397/24330111/16f7d98c-1218-11e7-81fc-a73bcf928702.png)

for example, if you set start-horizontal = 18, end-horizontal = 19, start-vertical = 4, end-vertical = 5, then all the tiles included in this "area" are downloaded and processed (h18v4, h18v5, h19v4, h19v5), and **mosaicing is done on the fly on the outputs**. 

Consider also that if you provide a shapefile / raster file representing your desired study area, `MODIStsp ` **automatically crops the outputs** to that area, thus saving disk space.

To do that, select `resized` in the  `output extent` and then click on `Load extent from....` to submit a spatial file representing your study area. 

![immagine](https://cloud.githubusercontent.com/assets/4480397/24330160/e4f728ec-1218-11e7-8598-06665a775738.png)

HTH, 

Lorenzo
