### ISSUE TITLE
FAILED TO LOAD RGtk2 dynamic library  for MODIStsp

### ISSUE THREAD

**Issue by Efrain73** [lbusett/MODIStsp#69]
To install RGtk2 for MODIStsp
using R version 3.3.3 on Platform: x86_64-w64-mingw32/x64 (64-bit)

Executing
library(gWidgetsRGtk2)

This error comes out:   

Carregando pacotes exigidos: RGtk2
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/SIGYURY/Documents/R/win-library/3.3/RGtk2/libs/i386/RGtk2.dll':
  LoadLibrary failure:  No se puede encontrar el módulo especificado.
trying URL 'http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip'
Content type 'application/zip' length 24516284 bytes (23.4 MB)
downloaded 23.4 MB
Learn more about GTK+ at http://www.gtk.org
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Carregando pacotes exigidos: gWidgets
Carregando pacotes exigidos: cairoDevice
Warning messages:
1: Failed to load RGtk2 dynamic library, attempting to install it. 
2: In dir.create(config_path, recursive = TRUE) :
  'C:\Users\SIGYURY\Documents\R\win-library\3.3\RGtk2\gtk\i386\etc\gtk-2.0' already exists
--------------------------------------------------
FAILED TO LOAD RGtk2 dynamic library
How do I solve this?
Thank you

**Comment by lbusett** [comment]
HI, 

Did you already try to Install GTK+ as requested and then closing and reopening RStudio and trying to reload the library ? 

If doing that doesn't solve the issue, you can try following these instructions: 

https://www.stat.auckland.ac.nz/%7Ekimihia/rgtk2

, starting from "Download the GTK+ all-in-one bundle"

**Comment by Efrain73** [comment]
Thank you   lbusett
Very good
The problem was:
RStudio doesn't automatically restart after installing GTK+

I fiz
Restart in Rstudio
in menu 
   Session: 
         restart R

ready

**Comment by lbusett** [comment]
ok. Glad that you solved this.
