### ISSUE TITLE
 Data download Problems

### ISSUE THREAD

**Issue by Efrain73** [lbusett/MODIStsp#70]
With  HTTP
 Trying to reach http server - attempt 25
 Error in curl::curl_fetch_memory(url, handle = handle) : 
.
.
.

How much time do I need to download a scene?

 With FTP
  Does not finish downloading
  Never reaches 100%
--------------------------------------------------------------------------------------
Connection #0 to host ladsweb.nascom.nasa.gov left intact
[Tue Apr 04 16:51:54 2017] Downloading Terra Files for date 2000_02_18 : 1 of 1
  |=================                                                                         |  18%
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
In addition: There were 37 warnings (use warnings() to see them)
[Tue Apr 04 17:11:54 2017] Download Error - Retrying...
[Tue Apr 04 17:11:55 2017] Downloading Terra Files for date 2000_02_18 : 1 of 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
[Tue Apr 04 17:12:08 2017] Download Error - Retrying...
[Tue Apr 04 17:12:09 2017] Downloading Terra Files for date 2000_02_18 : 1 of 1
  |=============                                                                             |  15%

--------------------------------------------------------------------------------------------------

Until now I can not download any image

**Comment by lbusett** [comment]
Hi, 

    two things:

1) Did you see this advice at the top of the main page ?

"If you have trouble downloading via http, please visit your earthdata "profile" page, click on "My Applications" and ensure that "LP DAAC Data Pool" is authorized. If not, click on "Approve More Applications", search for it in the list and approve it."

If not, please follow the instructions reported.

2) If you have problems on http download, try usinf ftp download instead.

Lorenzo

**Comment by lbusett** [comment]
Hi Efrain73,

    I see now that you already tried with `ftp` download. Can you tell me after how long you get the "Timeout was reached" message ? 

Lorenzo

**Comment by Efrain73** [comment]
Thank you
The problem was to wait
Like 30 min to start downloading

Now everything works fine

**Comment by Efrain73** [comment]
I am trying to install MODIStsp, on a new computer and this error comes out
Apparently does not recognize it

> install_github("lbusett/MODIStsp")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached

**Comment by lbusett** [comment]
regarding problem #1, it doesn't usually happen, unless your network is particularly slow. 

Regarding problem #2, that never happened to me. Could you try installing some other package from github (e.g., `install_github("hadley/devtools") ? Also, did you install the last version of Rtools

**Comment by Efrain73** [comment]
> install_github("hadley/devtools")
Error: could not find function "install_github"

**Comment by lbusett** [comment]
you have to either load library devtools beforehand, or run: 

`devtools::install_github("hadley/devtools")`
