### ISSUE TITLE
problem  install MODIStsp 

### ISSUE THREAD

**Issue by Efrain73** [lbusett/MODIStsp#71]
Why does this error come out?
It is the internet?

> library(devtools)
> install_github("lbusett/MODIStsp")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached

**Comment by lbusett** [comment]
Working for me.  Seems like a network problem Could you retry later and if it still doesn't work share your session_info ?

**Comment by Efrain73** [comment]
I solved it by copying the MODIS files from my other computer

**Comment by Efrain73** [comment]
Now does not connect

> library(MODIStsp)
> MODIStsp()
GDAL version in use: 2.0.1 
[Sat Apr 08 14:51:55 2017] Retrieving list of files from NASA server
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 2
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 3
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 4
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 5
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 6
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 7
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 8
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 9
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 10
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 11
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 12
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 13
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 14
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 15
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 16
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 17
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 18
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 19
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 20
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 21
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 22
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 23
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 24
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 25
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 26

**Comment by lbusett** [comment]
It really seems that you have some kind of problem on your network. 
However, could you try to save your current processing options and send us the JSON file ?

**Comment by Efrain73** [comment]
Sending the JSON file

Thank you

2017-04-08 18:17 GMT-03:00 Lorenzo Busetto <notifications@github.com>:

**Comment by Efrain73** [comment]
{
 "sel_prod": "Vegetation Indexes_16Days_250m (M*D13Q1)",
"sensor": "Terra",
"prod_version": "6",
"start_date": "2002-01-01",
"end_date": "2017-04-07",
"bandsel": [      1,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0 ],
"indexes_bandsel": [      0,      0,      0,      0 ],
"quality_bandsel": [      0,      0,      0,      0,      0,      0,      0,      0,      0 ],
"start_x":     11,
"end_x":     11,
"start_y":     10,
"end_y":     10,
"user": "",
"password": "",
"use_aria": false,
"download_server": "ftp",
"download_range": "full",
"proj": "Latlon WGS84",
"user_proj4": "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
"out_res_sel": "Native",
"out_res": "native",
"full_ext": "Full Tiles Extent",
"resampling": "near",
"out_format": "ENVI",
"ts_format": "ENVI Meta Files",
"rts": "Yes",
"compress": {
 "None": "None" 
},
"nodata_change": "Yes",
"scale_val": "No",
"delete_hdf": "No",
"reprocess": "No",
"bbox": [ null, null, null, null ],
"out_folder": "C:\\MODIS_Time_series",
"out_folder_mod": "C:\\MODIS_HDF",
"MODIStspVersion": "1.3.2",
"custom_indexes": [] 
}

**Comment by lbusett** [comment]
Hi, 

   I don't know if you solved this. However, concerning other problems with timeouts I did an update to increase the max time allowed for download, to prevent incomplete downloading on slow connections. You can try updating MODIStsp to see if it works better for you. 
I'd also suggest you to install aria2c on your machine to improve download speed (To download it and install it, see: aria2.github.io/)

**Comment by Efrain73** [comment]
Hi thanks
I still can not solve it on my other computer

**Comment by lbusett** [comment]
did you try updating all "R" packages ?

**Comment by lbusett** [comment]
Also, have a look at this:

https://github.com/jeroen/curl/issues/72

It could be a DNS settingd problem on your "second" PC.

**Comment by lbusett** [comment]
Hi Efrain, 

   could you try to access this address on your browser ? 

ftp://ladsweb.nascom.nasa.gov/allData/5/MOD09A1/

and tell me if it is connecting properly ?

However, I am too noticing instability on ftp connection, recently. I'd suggest you to try to switch to http, using aria2c to speed-up things.

**Comment by MarksMoura** [comment]
GDAL version 2.1.1
Error in MODIStsp() : 
  Your local GDAL installation does not support HDF4 format. Please install HDF4 support and recompile GDAL.


How resolving??

**Comment by ggranga** [comment]
Dear @MarksMoura,
it depends on the OS you are using. If you are using a Linux distribution which does not provide precompiled versions of GDAL with HDF4 support, you have first to install HDF4 (the package name depends on the distribution), and then to manually compile GDAL adding `--with-hdf4` to `configure` parameters. In Windows, you have to select package `hdf4` during OsGeo4W installation.
If you have further requests on that, please open a specific issue and provide more detailed information about your operating system and GDAL installation.

**Comment by Efrain73** [comment]
Hi  lbusett
I think if it can be accessed,
But with several attempts

ftp://ladsweb.nascom.nasa.gov/allData/5/MOD09A1/

FTP Directory: ftp://ladsweb.nascom.nasa.gov/allData/5/MOD09A1/

[DIRUP] Parent Directory 
[DIR]  2000 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2001 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2002 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2003 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2004 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2005 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2006 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2007 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2008 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2009 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2010 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2011 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2012 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2013 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2014 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2015 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2016 . . . . . . . . . . . . . . Apr 21 17:30        
[DIR]  2017 . . . . . . . . . . . . . . Apr 21 17:30        
[FILE] NOTICE . . . . . . . . . . . . . Jan 01  1970   1401  [VIEW] [DOWNLOAD]

**Comment by lbusett** [comment]
Ok, then I think you really have problems with your network. 
You could try to temporarily turn off firewall and antivirus to see if access to the FTP speeds-up. 

Also, you could try setting the DNS of your internet connection to the google ones (8.8.8.8 and 8.8.4.4)
