### ISSUE TITLE
Not downloading images from NASA server

### ISSUE THREAD

**Issue by senani** [lbusett/MODIStsp#74]
Hi 
I am getting following error when I execute following code;

MODIStsp() 

## Error

GDAL version in use:2.0.1
[Wed May 17 09:39:38 2017] Retrieving list of files from NASA server
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 2

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
Trying to reach ftp server - attempt 3
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
Trying to reach ftp server - attempt 4
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

Information for my R session is:
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MODISTools_0.95.1    MODIStsp_1.3.2       gWidgetsRGtk2_0.0-83 cairoDevice_2.24     gWidgets_0.0-54     
[6] RGtk2_2.20.33       

loaded via a namespace (and not attached):
 [1] hash_2.2.6        Rcpp_0.12.10      magrittr_1.5      raster_2.5-8      gdalUtils_2.0.1.7 lattice_0.20-35  
 [7] R6_2.2.1          foreach_1.4.3     stringr_1.2.0     plyr_1.8.4        httr_1.2.1        xts_0.9-7        
[13] tools_3.4.0       rgdal_1.2-7       grid_3.4.0        data.table_1.10.4 pacman_0.4.6      R.oo_1.21.0      
[19] rgeos_0.3-23      iterators_1.0.8   RJSONIO_1.3-0     R.utils_2.5.0     bitops_1.0-6      codetools_0.2-15 
[25] curl_2.6          RCurl_1.95-4.8    sp_1.2-4          stringi_1.1.5     compiler_3.4.0    R.methodsS3_1.7.1
[31] XML_3.98-1.7      zoo_1.8-0

**Comment by lbusett** [comment]
Hi Senani, 

    could you please save and send us also your "options" JSON file ? 

additionally: 

    1) Please visit your earthdata "profile" page, click on "My Applications" and ensure that "LP DAAC Data Pool" is authorized. If not, click on "Approve More Applications", search for it in the list and approve it. 

    2) Did you try downloading also via `ftp` ? Are you having the same issues ? 

    3) Are you connecting to the internet via a proxy, or are you behind a "strict" firewall ? 
  
    4) Does connecting to the NASA lpdaac data pool folders from a browser "work" (e.g., https://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.006/2000.03.03/)? 

Lorenzo

**Comment by lbusett** [comment]
Hi Senani, 

   from your mail reply, it definitely seems that you don't have access to the NASA servers on your network, due to maybe some firewall/proxy restrictions. 

Could you try also to access to the following addresses ?  

ftp://ladsweb.nascom.nasa.gov/allData/5/MOD09A1/2014/
http://e4ftl01.cr.usgs.gov/MOLT/MOD09A1.005/

Lorenzo

**Comment by senani** [comment]
Hi Lorenzo,
I can access the link you sent. See below screen printout

[image: Inline image 1]





*Senani Karunaratne* | PhD



W: https://sites.google.com/site/senanikarunaratnelab/home



Google Scholar
<https://scholar.google.com.au/citations?user=hYkyuMoAAAAJ&hl=en>



Researchgate <https://www.researchgate.net/profile/Senani_Karunaratne>


*P* *Please consider the environ**ment before  printing this e-mail*

**Comment by lbusett** [comment]
Hi Senani, 

    the image didn't arrive but no problem. It seems possible that you have problems related to proxy/firewalling. Could you try this command ? 

```
library(httr)
GET("http://had.co.nz")
```

Lorenzo

**Comment by senani** [comment]
Hi Lorenzo,
Morning! This is the error message I got. Can you please let me know how I
can fix it or what I should inform to our network Admin person

> library(httr)
> GET("http://had.co.nz")
Error in curl::curl_fetch_memory(url, handle = handle) :
  Timeout was reached



*Senani Karunaratne* | PhD



W: https://sites.google.com/site/senanikarunaratnelab/home



Google Scholar
<https://scholar.google.com.au/citations?user=hYkyuMoAAAAJ&hl=en>



Researchgate <https://www.researchgate.net/profile/Senani_Karunaratne>


*P* *Please consider the environ**ment before  printing this e-mail*

**Comment by lbusett** [comment]
Hi Senani, 

  it's probable that you are connecting to the internet through a server. To solve the problem, you should: 

1) Ask to your IT the IP address and port of the server
2) before launching MODIStsp, run the following commands: 

```
    library(httr)
    set_config(use_proxy(url="XXX.XXX.XXX.XXX", port=YYYY))
```

(substitute XXX.XXX.XXX.XXX and YYYY with the IP address and port number of the proxy, respectively)

After doing that, launching the command 
```
    GET("http://had.co.nz")
```

shouln't give you an error anymore. If so, MODIStsp will probably work. 

HTH, 

Lorenzo

**Comment by senani** [comment]
Hi Lorenzo,
Thanks and I will talk to my net work admin tomorrow.

BTW, I already passed info about your package to Sydney Uni, my previous
group where they use MODIS images for their statistical and process-based
models. It's very useful and user friend. Great work!

Senani



*Senani Karunaratne* | PhD



W: https://sites.google.com/site/senanikarunaratnelab/home



Google Scholar
<https://scholar.google.com.au/citations?user=hYkyuMoAAAAJ&hl=en>



Researchgate <https://www.researchgate.net/profile/Senani_Karunaratne>


*P* *Please consider the environ**ment before  printing this e-mail*

**Comment by lbusett** [comment]
Hi Senani, 
  
     ok. By the way: I noticed that in the previous post I wrote "server" instead of "proxy". What you need is the IP address of your proxy (I corrected the comment, now). 

Lorenzo

**Comment by senani** [comment]
thanks and its noted!



*Senani Karunaratne* | PhD



W: https://sites.google.com/site/senanikarunaratnelab/home



Google Scholar
<https://scholar.google.com.au/citations?user=hYkyuMoAAAAJ&hl=en>



Researchgate <https://www.researchgate.net/profile/Senani_Karunaratne>


*P* *Please consider the environ**ment before  printing this e-mail*

**Comment by lbusett** [comment]
Hi Senani, 
  just wanted to ask you if in the end you solved this !

Lorenzo

**Comment by senani** [comment]
Hi Lorenzo,
Its working properly. I am using another network so having no issues. A
couple of other questions. I downloaded annual GPP and NPP for the entire
Australia - basically tile by tile. For NPP it says "PsnNet". Is it
correct? Also both annual GPP and NPP only available until 2014. Maybe
server is not updated for 2015 and 2016.

I am also downloading vegetation indices namely monthly aggregated data and
it seems like working all good for me.

If I have any questions will let you know. Thanks again for your help!

Thanks.

Regards,

Senani



*Senani Karunaratne* | PhD



W: https://sites.google.com/site/senanikarunaratnelab/home



Google Scholar
<https://scholar.google.com.au/citations?user=hYkyuMoAAAAJ&hl=en>



Researchgate <https://www.researchgate.net/profile/Senani_Karunaratne>


*P* *Please consider the environ**ment before  printing this e-mail*

**Comment by lbusett** [comment]
Hi Senani, 

 glad it works ! 
Concerning NPP/GPP, the product should provide layers: 

- Gpp_1km: Gross Primary Production
- PsnNet_1km: Net Photosynthesis (GPP – maintenance respiration)

Regarding "years" availability, it probably depends on version. You can have a look at what "years" are available for the different versions checking on
[https://e4ftl01.cr.usgs.gov/MOLT/](https://e4ftl01.cr.usgs.gov/MOLT/)

Lorenzo

**Comment by senani** [comment]
Thanks again!



*Senani Karunaratne* | PhD



W: https://sites.google.com/site/senanikarunaratnelab/home



Google Scholar
<https://scholar.google.com.au/citations?user=hYkyuMoAAAAJ&hl=en>



Researchgate <https://www.researchgate.net/profile/Senani_Karunaratne>


*P* *Please consider the environ**ment before  printing this e-mail*

**Comment by Bhaskar02** [comment]
tif = runGdal(product="MOD11A2",begin="2009001",end="2009001", extent=ext,SDSstring="101100",job = "MOD11A2.006") # 6.4 MB
No collection specified, getting the newest for MOD11A2 
########################
outProj          =  asIn  (if applicable, derived from Raster*/Spatial*/sf* object)
pixelSize        =  asIn  (if applicable, derived from Raster* object)
resamplingType   =  near 
Output Directory =  I:/Aerosol/Aerosol_55/MOD11A2.006 
########################
Downloading structure on 'LAADS' for: MOD11A2.006
Error in file(file, "rt") : cannot open the connection
Error in file(file, "rt") : cannot open the connection
