### ISSUE TITLE
Error when using `spatial_file_path`

### ISSUE THREAD

**Issue by dk-forestry** [lbusett/MODIStsp#75]
I'm trying to download MODIS data using the `spatial_file_path`-option. When using the shapefile manually in the GUI to "Load extent from a spatial file", everything works as expected. However, when I provide it as an argument like this

`MODIStsp(gui = FALSE, options_file = "options.json", spatial_file_path = "shapefile.shp")`

I get the following error: 

`Error in as.vector(x) : no method for coercing this S4 class to a vector`

Would you have any ideas what might be the problem here?

**Comment by ggranga** [comment]
Dear @dk-forestry,
thank you for signaling it; i made a change in the code which should have solved the problem. Please try to update your MODIStsp installation from GitHub (`devtools::install_github("lbusett/MODIStsp")`).

**Comment by dk-forestry** [comment]
Thank you, it now works with the updated version. :)

By the way, I noticed two things related to this:

1. In the example for `Non-Interactive Execution and scheduled processing` the following code is used: 

`# Create a character array containing a list of shapefiles (or other spatial files)`
`extent_list = list.files("X:/path/containing/some/shapefiles/", "\\.shp$")`

Shouldn't `list.files` include the argument `full.names = TRUE`? 

2. If the argument for `spatial_file_path` points to a non-existing file, the user receives the following error:

> Error in MODIStsp(gui = FALSE, options_file = option_file, spatial_file_path = single_shape) : 
  Error in bbox_from_file(file_path = spatial_file_path, out_crs = general_opts$user_proj4) : 
  File format not recognized by GDAL or OGR. 
> Details: Error in CRS(gsub("'", "", cmd_output)) : 
  PROJ4 argument-value pairs must begin with +: ERROR 1: ERROR - failed to load SRS definition from NA

Maybe it would make sense to check somewhere if the shapefile exists and give a clear error if not?

**Comment by lbusett** [comment]
Both good points ! Thanks for the suggestions !
We'll implement them in the next release. 

Lorenzo

**Comment by dk-forestry** [comment]
I was working and downloading some data with the new version from above and noticed something else related to the `spatial_file_path`. 

Assuming I have a shapefile called `studyarea.shp`, then a folder called `studyarea` is created in the Main output folder. So far, so good. However, if `MODIStsp` is run again (with exactly the same option file and shapefile), a new folder called `studyarea_1` is created, and all data is reprocessed (even though the `ReProcess Existing Data` was set to `No`. 

I imagine that this behavior is unexpected, because during periodic data downloads or this [workaround](https://github.com/lbusett/MODIStsp/issues/66#issuecomment-285980983) the same data would be created over and over (until the HDD is at its limits ;) ). Is there maybe a fix or workaround?

**Comment by lbusett** [comment]
Definitely a bug in the spatial_file_path option. We'll investigate it ASAP.

**Comment by ggranga** [comment]
This was an expected behaviour: the intention was to create separate folders in case this function was run in a cycle, in which spatial files had the same basename (being placed in different folders).
Actually this is an uncommon situation, while scheduled download appears to be a more common one. So this funzionality was remove: now the original folder name is maintained.

**Comment by dk-forestry** [comment]
Thanks for the explanation and the changes to the code! :)
