### ISSUE TITLE
Can't download multiple Image via GUI

### ISSUE THREAD

**Issue by SpikeGuard** [lbusett/MODIStsp#76]
When i use GUI to download image in download only first image form that time period, however when i use command in R script without GUI it's can load multiple image.
 
Can someone help me FIX this.

**Comment by lbusett** [comment]
Hi, 

    that's strange. Could you please save your processing options from the GUI and send us the JSON file ?

**Comment by SpikeGuard** [comment]
Another issue I try to use Standalone non-interactive execution but an error occur 
FEtal error : cannot open file 'C:Users\...\MODIStsp_launcher.R no such file or directory
I assume that I need to add path_to_MODIStsp_bat\MODIStsp.bat -g -s "X:/yourpath/youroptions.json" in Target:  in Shortcut file of MODIStsp.bat right ?
when it's only  path_to_MODIStsp_bat\MODIStsp.bat it's can work properly

**Comment by ggranga** [comment]
The proble is due to the fact that the batch file needs to be edited in order to specify the R version which you are using. In commit https://github.com/lbusett/MODIStsp/commit/b0f2b8a59bc40ca20feb5f83209fdb569d9f66c3 I edited the documentation in order to specify that:
> In the case you encountered an error launching that, please edit the 4th line of the file `path_to_MODIStsp_bat\MODIStsp.bat`, replacing the R version with the one that you are using.

**Comment by SpikeGuard** [comment]
It's still not work when i add only -g  it's work and ask for option file but when i add -s and option file path
now error occur  Fatal error: cannot open file 'D:\..\MODIStsp_launcher.R': No such file or direc
tory

**Comment by SpikeGuard** [comment]
Also if i try to change command in batch file like this
:Run
%Rscript_dir%\Rscript.exe C:\Users\MONCHAI\Documents\R\win-library\3.4\MODIStsp\ExtData\Launcher\MODIStsp_launcher.R %gui% %options_File% %spatial_file_path%
goto End

Fetal error: are gone but new occur
:Run
%Rscript_dir%\Rscript.exe C:\Users\MONCHAI\Documents\R\win-library\3.4\MODIStsp\ExtData\Launcher\MODIStsp_launcher.R %gui% %options_File% %spatial_file_path%
goto End

**Comment by ggranga** [comment]
For the first problem, retry after https://github.com/lbusett/MODIStsp/commit/6716f7b1c5afc4d6f2532d969a7c6c646784e0d0.
For the second, I am not able to reproduce it. Please try having R, MODIStsp package and json file all on the same device.

**Comment by SpikeGuard** [comment]
ok i do it now it has the same error 
Fetal error: are gone but new occur
Loading required package: MODIStsp
Error in load(options_file) :
bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file 'test.json' has magic number '{ "'
Use of save versions prior to 2 is deprecated
Execution halted
 R, MODIStsp package and json file are on the same device.

**Comment by ggranga** [comment]
It seems a problem related to the RJSONIO package (used to read json setting files): a magic number is searched in a json, which is a plain text file. No way to solve it without changing the way json files are read:
we will check in future if a rapid solutio is possible. Now, to schedule process on Windows you can try using [taskscheduleR](https://www.r-bloggers.com/new-rstudio-add-in-to-schedule-r-scripts/) package.
