### ISSUE TITLE
invalid JSON input error message

### ISSUE THREAD

**Issue by mecolby5** [lbusett/MODIStsp#78]
I am new to this package and having some issues opening up the interactive GUI.  
When I type the command:
 MODIStsp()

I get this error message:
GDAL version in use:2.0.1
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input

I don't have any experience with JSON and can't seem to find a helpful post elsewhere.  
Any help is much appreciated!

**Comment by lbusett** [comment]
Strange... Does this happen "out of the box" (that is, immediately after installing MODIStsp) ? What version of "R" are you using ? Also, could you please try to update all you packages (`update.packages()`) and the remove and reinstall `MODIStsp` ?

Lorenzo

**Comment by mecolby5** [comment]
Thank you, removing and reinstalling the package solved it. I am running R 3.4.  I had run the interactive GUI a couple times and then got this error after.

Thanks for the quick fix!
