### ISSUE TITLE
Unable to connect to Server

### ISSUE THREAD

**Issue by mecolby5** [lbusett/MODIStsp#79]
I have been unable to connect to the server, for both ftp and http connection options. It shows me this error:
Trying to reach http server - attempt 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server

This error continues to come up 50-100x.

I've tried the 3-4 fixes listed under your troubleshooting section, none of which have worked thus far.

My internet is really really slow, ie 0.6 mbps, could this be the issue?
I'm also running internet off of a cellular hotspot, could there be special proxy settings associated with this?

Thanks for the help!

**Comment by lbusett** [comment]
Hi. Given the error message, I'd say you have a proxy problem. Slow Internet would instead give you "timeout" errors. I don't know however if/how you could set proxy information for a mobile hot spot.
