### ISSUE TITLE
What-is-LatLonWGS84-for-MODIS

### ISSUE THREAD

**Issue by Rmodis** [lbusett/MODIStsp#80]
I tried several times to test MODISstp. But i was not success. Already,
i find when i select reprojection section, choose LatLonWGS84,
i wrote wrong value for pixel size. I will be appreciate if send me the link that i find this values

**Comment by ggranga** [comment]
Can you better detail your problem, attaching the json which you are using?

**Comment by lbusett** [comment]
This is a bit unclear. However, I'll try to answer. If you want to reproject to LatLonWGS84 and don't want to keep the mative resolution of the dataset, then you have to specify the output resolution in **decimal degrees**. See here for some info about how decimal degrees relate to metric distances at different latitudes: https://en.wikipedia.org/wiki/Decimal_degrees

**Comment by Rmodis** [comment]
Thanks a lot for your good guidance. My mistake was at pixel size when i used reprojection option. With link how convert to decimal degree, it worked.
