### ISSUE TITLE
 Error in reading shapefile in MODIStsp

### ISSUE THREAD

**Issue by dpoursanidis** [lbusett/MODIStsp#81]
[1] "D:\\SierraNevadaMODIS_LST\\AOI.shp"
 [Thu Jun 29 18:19:48 2017] Retrieving the Extent, please wait... Error in if (digits < 0L) digits <- 6L else { : missing value where TRUE/FALSE needed Attached the shapefile (created in ArcGIS).

Any idea ?
[SierraNevadaMODIS_LST.zip](https://github.com/lbusett/MODIStsp/files/1113010/SierraNevadaMODIS_LST.zip)

**Comment by lbusett** [comment]
Hi. 
    the shapefile opens correctly for me when I select it from the "Load Extent from a spatial file" button (Despite some error messages which we should disable in the future). 

Where do you get that error ? 

Lorenzo

**Comment by dpoursanidis** [comment]
That error appear in the r studio console and still exists

**Comment by lbusett** [comment]
sorry, I don't get it. What do you mean by "in the Rstudio console" ? When is it happening ? Does it affect correct completion of the processing ? Could you please explain more precisely what's happening ?

**Comment by dpoursanidis** [comment]
![rstudio](https://user-images.githubusercontent.com/8640644/27739815-8d522bc8-5db8-11e7-9350-ff78981e4bb5.jpg)

**Comment by dpoursanidis** [comment]
You can see in the above image the errors i recieve in the RStudio console (lower left panel).
Also, using the shapefile, the output projection is not recognized automatically.

**Comment by lbusett** [comment]
So, this happens when you re-open MODIStsp, after a processing in which you used "AOI.shp" as your "extent" layer, right ? 

It's a strange problem... I'd  suggest you to try to re-install MODIStp. While you are at it, I'd suggest you to install the `devel` version from github, since it contains several bug fixes made after release of v1.3.2. You can do that by: 

    remove.packages("MODIStsp")
    install.packages("devtools")
    install_github("lbusett/MODIStsp")

**Comment by dpoursanidis** [comment]
![image](https://user-images.githubusercontent.com/8640644/27788527-ad115b88-5ff1-11e7-9d66-f6bffbcf9030.png)

Hi, i follow your steps and viola > 

The procedure entry point deflateSetHeader could not be located in the dynamic link library C:\msys64\mingw64\bin\libgio-2.0-0.dll

GTK+ has been downloaded and use after your instructions in the devel package (gtk+-bundle_2.22.1-20101227_win32)

**Comment by lbusett** [comment]
This is actually unrelated to MODIStsp. You are facing a problem with RGTk+, Please try to restart RStudio, and remove and try this:

Remove packages "gWidgets", "gWidgetsRGtk2" and "RGtk2" using remove.packages or from RStudio. Remove package "MODIStsp" in the same way, then: 
    
    update.packages()

Close and reopen RStudio; 

    install.packages("gWidgetsRGtk2"). 
    # Install GTK+ when asked - kill RStudio if necessary
Close and reopen RStudio; 

    library(gWidgetsRGtk2)
    library(devtools)
    install_github("lbusett/MODIStsp")

**Comment by dpoursanidis** [comment]
Seems that conflict exists with RGTk+

> library(gWidgetsRGtk2)
Loading required package: RGtk2
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/DPoursanides/Documents/R/win-library/3.4/RGtk2/libs/x64/RGtk2.dll':
  LoadLibrary failure:  Το %1 δεν είναι έγκυρη εφαρμογή Win32.

trying URL 'http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip'
Content type 'application/zip' length 25830230 bytes (24.6 MB)
downloaded 24.6 MB

Learn more about GTK+ at http://www.gtk.org
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Loading required package: gWidgets
Loading required package: cairoDevice
Warning messages:
1: Failed to load RGtk2 dynamic library, attempting to install it. 
2: In dir.create(config_path, recursive = TRUE) :
  'C:\Users\DPoursanides\Documents\R\win-library\3.4\RGtk2\gtk\x64\etc\gtk-2.0' already exists

**Comment by dpoursanidis** [comment]
Seems that after a reboot everything works perfect !

**Comment by lbusett** [comment]
Disconnetting the plug is often the best solution ! ;-)

**Comment by lbusett** [comment]
Can I close this, or do you still have problems with the shapefile ?

**Comment by dpoursanidis** [comment]
I believe that you can close it and if something new will appear i will let you know.
