### ISSUE TITLE
Error installing on R version 3.3.3 

### ISSUE THREAD

**Issue by hammao** [lbusett/MODIStsp#89]
_I got this error message_ 

**Error: package ‘RGtk2’ required by ‘gWidgetsRGtk2’ could not be found
In addition: Warning message:
package ‘gWidgetsRGtk2’ was built under R version 3.3.3** 

_i tried all method you suggested including_
http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip (OR
http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip if on
Win32)
, 

_Can you explain this further maybe i made some mistake while specifying environmental variable..._
> unzip the archive on a folder of your choice (e.g., C:\\Program Files\\GTK+), then add the path to the
> “bin” sub-folder (e.g., C:\\Program Files\\GTK+\\bin\\ to your system PATH environment variable.
> Restart your system and try loading again gWidgetsRGtk2

**Comment by lbusett** [comment]
Hi, 

    in order to give you better info, could you tell us which version of windows you are using ?

**Comment by hammao** [comment]
Thanks for the prompt reply 

Windows 10 x64

-------------------------------------------
Amao Abduljamiu O. (PhD)
Geosciences Department
King Fahd University of Petroleum and Minerals (KFUPM),
P. O. Box 1723 KFUPM, Dhahran 31261 Saudi Arabia
Tel. office +966138603240
Mobile: +966 535467527 
Skype: lakesido02
Email: amao@kfupm.edu.sa 
 Alt: lekisoft@gmail.com
--------------------------------------------

**Comment by lbusett** [comment]
To set the environment variable:

1)  Go to control Panel --> system --> settings --> advanced system settings --> Environment variables

2) In the "system variable" panel on the bottom select "path" and then "edit"

3) select "Path" and add a new entry to the "bin" subfolder of the folder where you unzipped the bindel (e.g., C:\RGTk\bin\)

4) for good measure, do the same on the "user variables" panel.

5) ok --> ok

6) reboot (or logout and reconnect - never understood if logging out is sufficient)

Let us know if you solved it ! 

By the way: what happens exactly if you do 

    install.packages(gWidgetsRGtk2)
    library(gWidgetsRGtk2) 

aren't you asked for installation of GTK+ ?

**Comment by hammao** [comment]
When i run this, i get the error below
```
install.packages(gWidgetsRGtk2)
library(gWidgetsRGtk2)
```
Error: package ‘RGtk2’ required by ‘gWidgetsRGtk2’ could not be found
In addition: Warning message:
package ‘gWidgetsRGtk2’ was built under R version 3.3.3

**Comment by hammao** [comment]
I tried these steps as recommended but still got back same error 

> 1.	Go to control Panel --> system --> settings --> advanced system settings --> Environment variables
> 2.	In the "system variable" panel on the bottom select "path" and then "edit"
> 3.	select "Path" and add a new entry to the "bin" subfolder of the folder where you unzipped the bindel (e.g., C:\RGTk\bin)
> 4.	for good measure, do the same on the "user variables" panel.
> 5.	ok --> ok
> 6.	reboot (or logout and reconnect - never understood if logging out is sufficient)

i got the following Error msg, thats after restarting my system.

> Error: package ‘RGtk2’ required by ‘gWidgetsRGtk2’ could not be found
> In addition: Warning message:
> package ‘gWidgetsRGtk2’ was built under R version 3.3.3 

I can send you screen shots...

**Comment by lbusett** [comment]
ok. can you try:

    install.packages("RGtk2")

ir should be installed automatically alongside  gWidgetsRGtk2, but it doesn't seem to be the case for you.

**Comment by hammao** [comment]
> install.packages("RGtk2")
Installing package into ‘C:/Users/hamma/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘RGtk2’ is not available (for R version 3.3.2)

**Comment by lbusett** [comment]
ok. The you can try: 

    install.packages("RGtk2",  type="source")
    
or 

    install.packages("RGtk2", dependencies=TRUE, repos='http://cran.rstudio.com/')

, or you could update "R" to 3.4.0 (which should work for sure).

**Comment by hammao** [comment]
Thanks alot... 
it is working now.

Thanks for all your help.

**Comment by lbusett** [comment]
You're welcome. 
 
by the way: for reference to other users: which solution worked, in the end ?

**Comment by hammao** [comment]
I updated "R" to 3.4.0 and installed install.packages("RGtk2", dependencies=TRUE, repos='http://cran.rstudio.com/ <http://cran.rstudio.com/>')
