### ISSUE TITLE
Error in MODIStsp

### ISSUE THREAD

**Issue by Rmodis** [lbusett/MODIStsp#90]
GDAL version 2.1.1
Error in MODIStsp() :
Your local GDAL installation does not support HDF4 format. Please install HDF4 support and recompile GDAL.

I use R in windows 7, and this package till yesterday had worked. But today it get this error.
i download HDF4 and install in windows, but i don`t know what can i do for the next step.
I will gratify if anybody help me.

**Comment by lbusett** [comment]
Hi. 

If MODIStsp was working before and you didn't reinstall/update it, it seems that something happened on your GDAL installation. Did you make any changes on your PC in the last days ?

**Comment by Rmodis** [comment]
Yes, unfortunately, two days i have problem with ArcGIS 9.3, uninstalled it. But i can not able to install it again. And now my MODIStsp find the problem.

**Comment by Rmodis** [comment]
Loading required package: gWidgetsRGtk2
Loading required package: RGtk2
Loading required package: gWidgets
Loading required package: cairoDevice
[Fri Jul 28 12:04:42 2017]Welcome to MODIStsp!

We will now search for a valid GDAL installation - please wait
(this will happen only once)
Scanning for GDAL installations...
Checking Sys.which...
Checking common locations...
GDAL version 2.1.1
Error in MODIStsp() : 
  Your local GDAL installation does not support HDF4 format. Please install HDF4 support and recompile GDAL.
In addition: Warning message:
package ‘gWidgetsRGtk2’ was built under R version 3.4.1 

after these commends, the main window of MODIStsp does not appear

**Comment by lbusett** [comment]
Ok. can you try this in "R" and send me the output ? 

    library(gdalUtils)
    gdal_setInstallation()
    getOption("gdalUtils_gdalPath")

**Comment by Rmodis** [comment]
I install R and r studio for last version, and OSGeo4W set up

**Comment by Rmodis** [comment]
for your command output is this:

[[1]]
[[1]]$path
[1] "C:/PROGRA~2/TerrSet/GDAL/bin/"

[[1]]$version
version 
"2.1.1" 

[[1]]$date
        date 
"2016-07-07" 

[[1]]$drivers
                   format_code read write update virtualIO subdatasets
1                  VRT-raster- TRUE  TRUE   TRUE      TRUE       FALSE
2                GTiff-raster- TRUE  TRUE   TRUE      TRUE        TRUE
3                 NITF-raster- TRUE  TRUE   TRUE      TRUE        TRUE
4               RPFTOC-raster- TRUE FALSE  FALSE      TRUE        TRUE
5              ECRGTOC-raster- TRUE FALSE  FALSE      TRUE        TRUE
6                  HFA-raster- TRUE  TRUE   TRUE      TRUE       FALSE
7             SAR_CEOS-raster- TRUE FALSE  FALSE      TRUE       FALSE
8                 CEOS-raster- TRUE FALSE  FALSE      TRUE       FALSE
9           JAXAPALSAR-raster- TRUE FALSE  FALSE      TRUE       FALSE
10                 GFF-raster- TRUE FALSE  FALSE      TRUE       FALSE
11                ELAS-raster- TRUE  TRUE   TRUE      TRUE       FALSE
12                 AIG-raster- TRUE FALSE  FALSE      TRUE       FALSE
13             AAIGrid-raster- TRUE  TRUE  FALSE      TRUE       FALSE
14      GRASSASCIIGrid-raster- TRUE FALSE  FALSE      TRUE       FALSE
15                SDTS-raster- TRUE FALSE  FALSE      TRUE       FALSE
16                DTED-raster- TRUE  TRUE  FALSE      TRUE       FALSE
17                 PNG-raster- TRUE  TRUE  FALSE      TRUE       FALSE
18                JPEG-raster- TRUE  TRUE  FALSE      TRUE       FALSE
19                 MEM-raster- TRUE  TRUE   TRUE     FALSE       FALSE
20                JDEM-raster- TRUE FALSE  FALSE      TRUE       FALSE
21                 GIF-raster- TRUE  TRUE  FALSE      TRUE       FALSE
22              BIGGIF-raster- TRUE FALSE  FALSE      TRUE       FALSE
23                ESAT-raster- TRUE FALSE  FALSE      TRUE       FALSE
24                 BSB-raster- TRUE FALSE  FALSE      TRUE       FALSE
25                 XPM-raster- TRUE  TRUE  FALSE      TRUE       FALSE
26                 BMP-raster- TRUE  TRUE   TRUE      TRUE       FALSE
27               DIMAP-raster- TRUE FALSE  FALSE      TRUE       FALSE
28              AirSAR-raster- TRUE FALSE  FALSE      TRUE       FALSE
29                 RS2-raster- TRUE FALSE  FALSE     FALSE        TRUE
30                SAFE-raster- TRUE FALSE  FALSE      TRUE       FALSE
31       PCIDSK-raster,vector- TRUE  TRUE   TRUE      TRUE       FALSE
32            PCRaster-raster- TRUE  TRUE   TRUE     FALSE       FALSE
33               ILWIS-raster- TRUE  TRUE   TRUE      TRUE       FALSE
34                 SGI-raster- TRUE  TRUE   TRUE     FALSE       FALSE
35             SRTMHGT-raster- TRUE  TRUE  FALSE      TRUE       FALSE
36            Leveller-raster- TRUE  TRUE   TRUE     FALSE       FALSE
37            Terragen-raster- TRUE  TRUE   TRUE     FALSE       FALSE
38                 GMT-raster- TRUE  TRUE  FALSE     FALSE       FALSE
39       netCDF-raster,vector- TRUE  TRUE   TRUE     FALSE        TRUE
40               ISIS3-raster- TRUE FALSE  FALSE      TRUE       FALSE
41               ISIS2-raster- TRUE  TRUE   TRUE      TRUE       FALSE
42                 PDS-raster- TRUE FALSE  FALSE      TRUE       FALSE
43               VICAR-raster- TRUE FALSE  FALSE      TRUE       FALSE
44                 TIL-raster- TRUE FALSE  FALSE      TRUE       FALSE
45                 ERS-raster- TRUE  TRUE   TRUE      TRUE       FALSE
46  JP2OpenJPEG-raster,vector- TRUE  TRUE  FALSE      TRUE       FALSE
47                 L1B-raster- TRUE FALSE  FALSE      TRUE        TRUE
48                 FIT-raster- TRUE  TRUE  FALSE      TRUE       FALSE
49                GRIB-raster- TRUE FALSE  FALSE      TRUE       FALSE
50                 RMF-raster- TRUE  TRUE   TRUE      TRUE       FALSE
51                MSGN-raster- TRUE FALSE  FALSE     FALSE       FALSE
52                 RST-raster- TRUE  TRUE   TRUE      TRUE       FALSE
53                INGR-raster- TRUE  TRUE   TRUE      TRUE       FALSE
54                GSAG-raster- TRUE  TRUE  FALSE      TRUE       FALSE
55                GSBG-raster- TRUE  TRUE   TRUE      TRUE       FALSE
56               GS7BG-raster- TRUE  TRUE   TRUE      TRUE       FALSE
57               COSAR-raster- TRUE FALSE  FALSE      TRUE       FALSE
58                 TSX-raster- TRUE FALSE  FALSE      TRUE       FALSE
59               COASP-raster- TRUE FALSE  FALSE     FALSE       FALSE
60                   R-raster- TRUE  TRUE  FALSE      TRUE       FALSE
61                 MAP-raster- TRUE FALSE  FALSE      TRUE       FALSE
62     KMLSUPEROVERLAY-raster- TRUE  TRUE  FALSE      TRUE       FALSE
63                CALS-raster- TRUE  TRUE  FALSE     FALSE       FALSE
64           SENTINEL2-raster- TRUE FALSE  FALSE      TRUE        TRUE
65                 MRF-raster- TRUE  TRUE   TRUE      TRUE       FALSE
66                 PNM-raster- TRUE  TRUE   TRUE      TRUE       FALSE
67                DOQ1-raster- TRUE FALSE  FALSE      TRUE       FALSE
68                DOQ2-raster- TRUE FALSE  FALSE      TRUE       FALSE
69              GenBin-raster- TRUE FALSE  FALSE      TRUE       FALSE
70                PAux-raster- TRUE  TRUE   TRUE     FALSE       FALSE
71                 MFF-raster- TRUE  TRUE   TRUE      TRUE       FALSE
72                MFF2-raster- TRUE  TRUE   TRUE     FALSE       FALSE
73             FujiBAS-raster- TRUE FALSE  FALSE     FALSE       FALSE
74                 GSC-raster- TRUE FALSE  FALSE      TRUE       FALSE
75                FAST-raster- TRUE FALSE  FALSE      TRUE       FALSE
76                  BT-raster- TRUE  TRUE   TRUE      TRUE       FALSE
77                 LAN-raster- TRUE  TRUE   TRUE      TRUE       FALSE
78                 CPG-raster- TRUE FALSE  FALSE     FALSE       FALSE
79                 IDA-raster- TRUE  TRUE   TRUE      TRUE       FALSE
80                 NDF-raster- TRUE FALSE  FALSE      TRUE       FALSE
81                 EIR-raster- TRUE FALSE  FALSE      TRUE       FALSE
82               DIPEx-raster- TRUE FALSE  FALSE      TRUE       FALSE
83                 LCP-raster- TRUE  TRUE  FALSE      TRUE       FALSE
84                 GTX-raster- TRUE  TRUE   TRUE      TRUE       FALSE
85              LOSLAS-raster- TRUE FALSE  FALSE      TRUE       FALSE
86                NTv2-raster- TRUE  TRUE   TRUE      TRUE        TRUE
87             CTable2-raster- TRUE  TRUE   TRUE      TRUE       FALSE
88                ACE2-raster- TRUE FALSE  FALSE      TRUE       FALSE
89              SNODAS-raster- TRUE FALSE  FALSE      TRUE       FALSE
90                 KRO-raster- TRUE  TRUE   TRUE      TRUE       FALSE
91             ROI_PAC-raster- TRUE  TRUE   TRUE      TRUE       FALSE
92                ENVI-raster- TRUE  TRUE   TRUE      TRUE       FALSE
93                EHdr-raster- TRUE  TRUE   TRUE      TRUE       FALSE
94                ISCE-raster- TRUE  TRUE   TRUE      TRUE       FALSE
95                 ARG-raster- TRUE  TRUE  FALSE      TRUE       FALSE
96                 RIK-raster- TRUE FALSE  FALSE      TRUE       FALSE
97             USGSDEM-raster- TRUE  TRUE  FALSE      TRUE       FALSE
98                 GXF-raster- TRUE FALSE  FALSE     FALSE       FALSE
99                 BAG-raster- TRUE FALSE  FALSE     FALSE       FALSE
100               HDF5-raster- TRUE FALSE  FALSE     FALSE        TRUE
101          HDF5Image-raster- TRUE FALSE  FALSE     FALSE       FALSE
102            NWT_GRD-raster- TRUE FALSE  FALSE      TRUE       FALSE
103            NWT_GRC-raster- TRUE FALSE  FALSE      TRUE       FALSE
104               ADRG-raster- TRUE  TRUE   TRUE      TRUE        TRUE
105                SRP-raster- TRUE FALSE  FALSE      TRUE        TRUE
106                BLX-raster- TRUE  TRUE  FALSE      TRUE       FALSE
107               SAGA-raster- TRUE  TRUE   TRUE      TRUE       FALSE
108                XYZ-raster- TRUE  TRUE  FALSE      TRUE       FALSE
109                HF2-raster- TRUE  TRUE  FALSE      TRUE       FALSE
110                OZI-raster- TRUE FALSE  FALSE      TRUE       FALSE
111                CTG-raster- TRUE FALSE  FALSE      TRUE       FALSE
112            E00GRID-raster- TRUE FALSE  FALSE      TRUE       FALSE
113               ZMap-raster- TRUE  TRUE  FALSE      TRUE       FALSE
114           NGSGEOID-raster- TRUE FALSE  FALSE      TRUE       FALSE
115               IRIS-raster- TRUE FALSE  FALSE      TRUE       FALSE
116     DB2ODBC-raster,vector- TRUE  TRUE   TRUE     FALSE       FALSE
                                                 format_name
1                                             Virtual Raster
2                                                    GeoTIFF
3                       National Imagery Transmission Format
4                           Raster Product Format TOC format
5                                            ECRG TOC format
6                                Erdas Imagine Images (.img)
7                                             CEOS SAR Image
8                                                 CEOS Image
9                 JAXA PALSAR Product Reader (Level 1.1/1.5)
10  Ground-based SAR Applications Testbed File Format (.gff)
11                                                      ELAS
12                                      Arc/Info Binary Grid
13                                       Arc/Info ASCII Grid
14                                          GRASS ASCII Grid
15                                               SDTS Raster
16                                     DTED Elevation Raster
17                                 Portable Network Graphics
18                                                 JPEG JFIF
19                                          In Memory Raster
20                                       Japanese DEM (.mem)
21                        Graphics Interchange Format (.gif)
22                        Graphics Interchange Format (.gif)
23                                      Envisat Image Format
24                               Maptech BSB Nautical Charts
25                                         X11 PixMap Format
26                      MS Windows Device Independent Bitmap
27                                                SPOT DIMAP
28                                 AirSAR Polarimetric Image
29                                    RadarSat 2 XML Product
30                               Sentinel-1 SAR SAFE Product
31                                      PCIDSK Database File
32                                      PCRaster Raster File
33                                          ILWIS Raster Map
34                                 SGI Image File Format 1.0
35                                       SRTMHGT File Format
36                                      Leveller heightfield
37                                      Terragen heightfield
38                                    GMT NetCDF Grid Format
39                                Network Common Data Format
40                   USGS Astrogeology ISIS cube (Version 3)
41                   USGS Astrogeology ISIS cube (Version 2)
42                                NASA Planetary Data System
43                                           MIPL VICAR file
44                                           EarthWatch .TIL
45                                    ERMapper .ers Labelled
46                JPEG-2000 driver based on OpenJPEG library
47                      NOAA Polar Orbiter Level 1b Data Set
48                                                 FIT Image
49                                     GRIdded Binary (.grb)
50                                      Raster Matrix Format
51                            EUMETSAT Archive native (.nat)
52                                         Idrisi Raster A.1
53                                         Intergraph Raster
54                         Golden Software ASCII Grid (.grd)
55                        Golden Software Binary Grid (.grd)
56                      Golden Software 7 Binary Grid (.grd)
57                COSAR Annotated Binary Matrix (TerraSAR-X)
58                                        TerraSAR-X Product
59                           DRDC COASP SAR Processor Raster
60                                       R Object Data Store
61                                          OziExplorer .MAP
62                                         Kml Super Overlay
63                                             CALS (Type 1)
64                                                Sentinel 2
65                                        Meta Raster Format
66                           Portable Pixmap Format (netpbm)
67                                      USGS DOQ (Old Style)
68                                      USGS DOQ (New Style)
69                            Generic Binary (.hdr Labelled)
70                                         PCI .aux Labelled
71                                         Vexcel MFF Raster
72                                  Vexcel MFF2 (HKV) Raster
73                                    Fuji BAS Scanner Image
74                                               GSC Geogrid
75                                         EOSAT FAST Format
76                       VTP .bt (Binary Terrain) 1.3 Format
77                                           Erdas .LAN/.GIS
78                                           Convair PolGASP
79                                   Image Data and Analysis
80                                         NLAPS Data Format
81                                         Erdas Imagine Raw
82                                                     DIPEx
83                         FARSITE v.4 Landscape File (.lcp)
84                                  NOAA Vertical Datum .GTX
85                         NADCON .los/.las Datum Grid Shift
86                                     NTv2 Datum Grid Shift
87                                  CTable2 Datum Grid Shift
88                                                      ACE2
89                             Snow Data Assimilation System
90                                                 KOLOR Raw
91                                            ROI_PAC raster
92                                        ENVI .hdr Labelled
93                                        ESRI .hdr Labelled
94                                               ISCE raster
95                                 Azavea Raster Grid format
96                                   Swedish Grid RIK (.rik)
97                        USGS Optional ASCII DEM (and CDED)
98                              GeoSoft Grid Exchange Format
99                                Bathymetry Attributed Grid
100                       Hierarchical Data Format Release 5
101                                             HDF5 Dataset
102                  Northwood Numeric Grid Format .grd/.tab
103               Northwood Classified Grid Format .grc/.tab
104                            ARC Digitized Raster Graphics
105                      Standard Raster Product (ASRP/USRP)
106                                     Magellan topo (.blx)
107                             SAGA GIS Binary Grid (.sdat)
108                                        ASCII Gridded XYZ
109                               HF2/HFZ heightfield raster
110                                   OziExplorer Image File
111                           USGS LULC Composite Theme Grid
112                                 Arc/Info Export E00 GRID
113                                           ZMap Plus Grid
114                              NOAA NGS Geoid Height Grids
115                             IRIS data (.PPI, .CAPPi etc)
116                                 IBM DB2 Spatial Database

[[1]]$python_utilities
[[1]]$python_utilities$`C:/PROGRA~2/TerrSet/GDAL/bin/`
character(0)



[[2]]
[[2]]$path
[1] "C:/PROGRA~2/IDRISI~1/GDAL/bin/"

[[2]]$version
 version 
"1.8dev" 

[[2]]$date
        date 
"2010-01-19" 

[[2]]$drivers
   format_code read write update virtualIO subdatasets
1     MG4Lidar TRUE FALSE  FALSE     FALSE       FALSE
2        MrSID TRUE FALSE  FALSE     FALSE       FALSE
3          VRT TRUE  TRUE   TRUE     FALSE       FALSE
4        GTiff TRUE  TRUE   TRUE      TRUE       FALSE
5         NITF TRUE  TRUE   TRUE      TRUE       FALSE
6       RPFTOC TRUE FALSE  FALSE     FALSE       FALSE
7          HFA TRUE  TRUE   TRUE      TRUE       FALSE
8     SAR_CEOS TRUE FALSE  FALSE     FALSE       FALSE
9         CEOS TRUE FALSE  FALSE     FALSE       FALSE
10  JAXAPALSAR TRUE FALSE  FALSE     FALSE       FALSE
11         GFF TRUE FALSE  FALSE      TRUE       FALSE
12        ELAS TRUE  TRUE   TRUE     FALSE       FALSE
13         AIG TRUE FALSE  FALSE     FALSE       FALSE
14     AAIGrid TRUE  TRUE  FALSE      TRUE       FALSE
15        SDTS TRUE FALSE  FALSE     FALSE       FALSE
16        DTED TRUE  TRUE  FALSE      TRUE       FALSE
17         PNG TRUE  TRUE  FALSE      TRUE       FALSE
18        JPEG TRUE  TRUE  FALSE      TRUE       FALSE
19         MEM TRUE  TRUE   TRUE     FALSE       FALSE
20        JDEM TRUE FALSE  FALSE     FALSE       FALSE
21         GIF TRUE  TRUE  FALSE      TRUE       FALSE
22      BIGGIF TRUE FALSE  FALSE      TRUE       FALSE
23        ESAT TRUE FALSE  FALSE     FALSE       FALSE
24         BSB TRUE FALSE  FALSE     FALSE       FALSE
25         XPM TRUE  TRUE  FALSE     FALSE       FALSE
26         BMP TRUE  TRUE   TRUE      TRUE       FALSE
27       DIMAP TRUE FALSE  FALSE     FALSE       FALSE
28      AirSAR TRUE FALSE  FALSE     FALSE       FALSE
29         RS2 TRUE FALSE  FALSE     FALSE       FALSE
30      PCIDSK TRUE  TRUE   TRUE      TRUE       FALSE
31    PCRaster TRUE  TRUE  FALSE     FALSE       FALSE
32       ILWIS TRUE  TRUE   TRUE      TRUE       FALSE
33         SGI TRUE  TRUE   TRUE     FALSE       FALSE
34     SRTMHGT TRUE  TRUE  FALSE      TRUE       FALSE
35    Leveller TRUE  TRUE   TRUE     FALSE       FALSE
36    Terragen TRUE  TRUE   TRUE     FALSE       FALSE
37        HDF4 TRUE FALSE  FALSE     FALSE       FALSE
38   HDF4Image TRUE  TRUE   TRUE     FALSE       FALSE
39       ISIS3 TRUE FALSE  FALSE     FALSE       FALSE
40       ISIS2 TRUE FALSE  FALSE     FALSE       FALSE
41         PDS TRUE FALSE  FALSE     FALSE       FALSE
42         TIL TRUE FALSE  FALSE     FALSE       FALSE
43         ERS TRUE  TRUE   TRUE     FALSE       FALSE
44         L1B TRUE FALSE  FALSE     FALSE       FALSE
45         FIT TRUE  TRUE  FALSE     FALSE       FALSE
46        GRIB TRUE FALSE  FALSE     FALSE       FALSE
47         RMF TRUE  TRUE   TRUE     FALSE       FALSE
48         WCS TRUE FALSE  FALSE     FALSE       FALSE
49         WMS TRUE FALSE  FALSE     FALSE       FALSE
50        MSGN TRUE FALSE  FALSE     FALSE       FALSE
51         RST TRUE  TRUE   TRUE     FALSE       FALSE
52        INGR TRUE  TRUE   TRUE     FALSE       FALSE
53        GSAG TRUE  TRUE  FALSE     FALSE       FALSE
54        GSBG TRUE  TRUE   TRUE     FALSE       FALSE
55       GS7BG TRUE FALSE  FALSE     FALSE       FALSE
56       COSAR TRUE FALSE  FALSE     FALSE       FALSE
57         TSX TRUE FALSE  FALSE     FALSE       FALSE
58       COASP TRUE FALSE  FALSE     FALSE       FALSE
59           R TRUE  TRUE  FALSE      TRUE       FALSE
60         PNM TRUE  TRUE   TRUE     FALSE       FALSE
61        DOQ1 TRUE FALSE  FALSE     FALSE       FALSE
62        DOQ2 TRUE FALSE  FALSE     FALSE       FALSE
63        ENVI TRUE  TRUE   TRUE      TRUE       FALSE
64        EHdr TRUE  TRUE   TRUE      TRUE       FALSE
65      GenBin TRUE FALSE  FALSE     FALSE       FALSE
66        PAux TRUE  TRUE   TRUE     FALSE       FALSE
67         MFF TRUE  TRUE   TRUE     FALSE       FALSE
68        MFF2 TRUE  TRUE   TRUE     FALSE       FALSE
69     FujiBAS TRUE FALSE  FALSE     FALSE       FALSE
70         GSC TRUE FALSE  FALSE     FALSE       FALSE
71        FAST TRUE FALSE  FALSE     FALSE       FALSE
72          BT TRUE  TRUE   TRUE     FALSE       FALSE
73         LAN TRUE FALSE  FALSE     FALSE       FALSE
74         CPG TRUE FALSE  FALSE     FALSE       FALSE
75         IDA TRUE  TRUE   TRUE     FALSE       FALSE
76         NDF TRUE FALSE  FALSE     FALSE       FALSE
77         EIR TRUE FALSE  FALSE     FALSE       FALSE
78       DIPEx TRUE FALSE  FALSE     FALSE       FALSE
79         LCP TRUE FALSE  FALSE      TRUE       FALSE
80         GTX TRUE  TRUE   TRUE      TRUE       FALSE
81      LOSLAS TRUE FALSE  FALSE      TRUE       FALSE
82        NTv2 TRUE  TRUE   TRUE      TRUE       FALSE
83         RIK TRUE FALSE  FALSE     FALSE       FALSE
84     USGSDEM TRUE  TRUE  FALSE     FALSE       FALSE
85         GXF TRUE FALSE  FALSE     FALSE       FALSE
86        HTTP TRUE FALSE  FALSE     FALSE       FALSE
87     NWT_GRD TRUE FALSE  FALSE     FALSE       FALSE
88     NWT_GRC TRUE FALSE  FALSE     FALSE       FALSE
89        ADRG TRUE  TRUE   TRUE      TRUE       FALSE
90         SRP TRUE FALSE  FALSE      TRUE       FALSE
91         BLX TRUE  TRUE  FALSE     FALSE       FALSE
92        SAGA TRUE  TRUE   TRUE      TRUE       FALSE
93         XYZ TRUE  TRUE  FALSE      TRUE       FALSE
94         HF2 TRUE  TRUE  FALSE      TRUE       FALSE
                                                format_name
1                         MrSID Generation 4 / Lidar (.sid)
2          Multi-resolution Seamless Image Database (MrSID)
3                                            Virtual Raster
4                                                   GeoTIFF
5                      National Imagery Transmission Format
6                          Raster Product Format TOC format
7                               Erdas Imagine Images (.img)
8                                            CEOS SAR Image
9                                                CEOS Image
10               JAXA PALSAR Product Reader (Level 1.1/1.5)
11 Ground-based SAR Applications Testbed File Format (.gff)
12                                                     ELAS
13                                     Arc/Info Binary Grid
14                                      Arc/Info ASCII Grid
15                                              SDTS Raster
16                                    DTED Elevation Raster
17                                Portable Network Graphics
18                                                JPEG JFIF
19                                         In Memory Raster
20                                      Japanese DEM (.mem)
21                       Graphics Interchange Format (.gif)
22                       Graphics Interchange Format (.gif)
23                                     Envisat Image Format
24                              Maptech BSB Nautical Charts
25                                        X11 PixMap Format
26                     MS Windows Device Independent Bitmap
27                                               SPOT DIMAP
28                                AirSAR Polarimetric Image
29                                   RadarSat 2 XML Product
30                                     PCIDSK Database File
31                                     PCRaster Raster File
32                                         ILWIS Raster Map
33                                SGI Image File Format 1.0
34                                      SRTMHGT File Format
35                                     Leveller heightfield
36                                     Terragen heightfield
37                       Hierarchical Data Format Release 4
38                                             HDF4 Dataset
39                  USGS Astrogeology ISIS cube (Version 3)
40                  USGS Astrogeology ISIS cube (Version 2)
41                               NASA Planetary Data System
42                                          EarthWatch .TIL
43                                   ERMapper .ers Labelled
44                     NOAA Polar Orbiter Level 1b Data Set
45                                                FIT Image
46                                    GRIdded Binary (.grb)
47                                     Raster Matrix Format
48                                 OGC Web Coverage Service
49                                      OGC Web Map Service
50                           EUMETSAT Archive native (.nat)
51                                        Idrisi Raster A.1
52                                        Intergraph Raster
53                        Golden Software ASCII Grid (.grd)
54                       Golden Software Binary Grid (.grd)
55                     Golden Software 7 Binary Grid (.grd)
56               COSAR Annotated Binary Matrix (TerraSAR-X)
57                                       TerraSAR-X Product
58                          DRDC COASP SAR Processor Raster
59                                      R Object Data Store
60                          Portable Pixmap Format (netpbm)
61                                     USGS DOQ (Old Style)
62                                     USGS DOQ (New Style)
63                                       ENVI .hdr Labelled
64                                       ESRI .hdr Labelled
65                           Generic Binary (.hdr Labelled)
66                                        PCI .aux Labelled
67                                        Vexcel MFF Raster
68                                 Vexcel MFF2 (HKV) Raster
69                                   Fuji BAS Scanner Image
70                                              GSC Geogrid
71                                        EOSAT FAST Format
72                      VTP .bt (Binary Terrain) 1.3 Format
73                                          Erdas .LAN/.GIS
74                                          Convair PolGASP
75                                  Image Data and Analysis
76                                        NLAPS Data Format
77                                        Erdas Imagine Raw
78                                                    DIPEx
79                        FARSITE v.4 Landscape File (.lcp)
80                                 NOAA Vertical Datum .GTX
81                        NADCON .los/.las Datum Grid Shift
82                                    NTv2 Datum Grid Shift
83                                  Swedish Grid RIK (.rik)
84                       USGS Optional ASCII DEM (and CDED)
85                             GeoSoft Grid Exchange Format
86                                    HTTP Fetching Wrapper
87                  Northwood Numeric Grid Format .grd/.tab
88               Northwood Classified Grid Format .grc/.tab
89                            ARC Digitized Raster Graphics
90                      Standard Raster Product (ASRP/USRP)
91                                     Magellan topo (.blx)
92                             SAGA GIS Binary Grid (.sdat)
93                                        ASCII Gridded XYZ
94                               HF2/HFZ heightfield raster

[[2]]$python_utilities
[[2]]$python_utilities$`C:/PROGRA~2/IDRISI~1/GDAL/bin/`
character(0)

**Comment by lbusett** [comment]
Could you try now to launch again MODIStsp ?

**Comment by Rmodis** [comment]
After installations , now it works. Thanks a lot
