### ISSUE TITLE
Use for process HDF data

### ISSUE THREAD

**Issue by dpoursanidis** [lbusett/MODIStsp#91]
Good morning

Is possible to use the tool to process HDF data that have been a priori downloaded from EARTHDATA ?

Best

**Comment by Rmodis** [comment]
Hi and good morning,

If i understand you, could be able open HDF in IDRISI directly by import option. or ArcGIS. In R you can use 

library(rgdal)
library(gdalUtils)
library(raster)

sds <- get_subdatasets('full/path/filename.hdf')
###### Isolate the name of the first sds####
name <- sds[1]
filename <- 'name/of/output/file.tif'
gdal_translate(sds[1], dst_dataset = filename)
#### Load the Geotiff created into R######
r <- raster(filename)

**Comment by dpoursanidis** [comment]
Thanks

I have custom code for HDF processing in R. The question is related to the MODIStsp package.

D.

**Comment by Rmodis** [comment]
Okey,

yes there is options that ask you need to pre-processing or not? resized based your coordinate rectangular and so on.... , and you can use bands or VI based on your product selection.

**Comment by lbusett** [comment]
Hi. Yes, you can use already downloaded files downloaded from LPDAAC. See here for some instructions: 

http://lbusett.github.io/MODIStsp/articles/faq.html#old-pdfs

**Comment by dpoursanidis** [comment]
Great ! Thanks (i have not seen the offline option).
