### ISSUE TITLE
Cannot download data on either server

### ISSUE THREAD

**Issue by mycid** [lbusett/MODIStsp#93]
I have installed the package and all dependencies but the MODIStsp is unable to reach either server almost every time. I say almost because once in a while it is able to download and process files from one or two segments in a large time series after failing to connect multiple times. My internet speed is not a problem. The following errors are (if starting with the http server):  

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 3994 milliseconds with 9322 bytes received
Trying to reach http server - attempt 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 3214 milliseconds with 0 bytes received
Trying to reach ftp server - attempt 1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 3806 milliseconds with 185871 bytes received

And so on. My internet connection is through a VPN; could this be the problem?

**Comment by lbusett** [comment]
Sorry for the problem. 

Could you please do two things: 

1) Save you processing options from the GUI and send me the file: 

2) Try running: 

`MODIStsp(test = 4)`

and 

`MODIStsp(test = 4)`

and report what happens ? 

Lorenzo

**Comment by mycid** [comment]
Thanks for the quick response. Attached is the JSON file. I tried running the test commands and both were not able to reach the server in 50 attempts nor receive any bytes before they timed out. 

[temptestTEjson.txt](https://github.com/lbusett/MODIStsp/files/1419669/temptestTEjson.txt)

**Comment by lbusett** [comment]
Ok. Seems like a connection problem.  Being on a VPN should not be a problem. What could be a problem is accessing the web through a proxy server. Is it like that ? 

Also,  what happens if you try to access this links from a browser ? 

http://e4ftl01.cr.usgs.gov/MOLA/MYD09A1.005/

ftp://ladsweb.nascom.nasa.gov/allData/5/MOD09A1/

**Comment by mycid** [comment]
Yes it must be. I have checked my browser settings and I'm not on any proxy server. My employers confirmed this. I checked my firewall settings and everything has the necessary permissions. Could it be related to some dependency problem or my geographical location? I accessed and could download files just fine from both links.

**Comment by lbusett** [comment]
Can you please share your session info?

**Comment by mycid** [comment]
Sure, here it is

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Chile.1252  LC_CTYPE=Spanish_Chile.1252    LC_MONETARY=Spanish_Chile.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Chile.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gWidgetsRGtk2_0.0-84 cairoDevice_2.24     gWidgets_0.0-54      RGtk2_2.20.33        MODIStsp_1.3.3.1    

loaded via a namespace (and not attached):
 [1] hash_2.2.6          Rcpp_0.12.13        magrittr_1.5        raster_2.5-8        gdalUtils_2.0.1.7  
 [6] lattice_0.20-35     R6_2.2.2            foreach_1.4.3       stringr_1.2.0       plyr_1.8.4         
[11] httr_1.3.1          xts_0.10-0          tools_3.4.2         parallel_3.4.2      rgdal_1.2-13       
[16] grid_3.4.2          data.table_1.10.4-2 pacman_0.4.6        R.oo_1.21.0         rgeos_0.3-25       
[21] iterators_1.0.8     RJSONIO_1.3-0       R.utils_2.5.0       bitops_1.0-6        codetools_0.2-15   
[26] curl_3.0            RCurl_1.95-4.8      sp_1.2-5            stringi_1.1.5       compiler_3.4.2     
[31] R.methodsS3_1.7.1   XML_3.98-1.9        zoo_1.8-0

**Comment by mycid** [comment]
An update: Without changing any of my JSON inputs or setup, today I am able to download several files from the ftp server with periodical timeouts. This means it has to be some sort of connection issue which is not immediately apparent. Maybe ample internet speed but to many intermittent connection interruptions. If downloading keeps getting interrupted I'll just ask a colleague in a less remote area to do the downloads for me. Thank you for your attentiveness; I think you've made a superb, very user-friendly package.

**Comment by lbusett** [comment]
Good that it is (more or less... ) solved. 

Two suggestions for you: 

1) I'd try again with http: if you rtied only on wednesday/thursday you may have been caughtin the maintenance downtime of lpdaac http. 

2) If you are "fluent" in building "R" packages you could clone the package to your machine, and then try to tweak the timeout settings of MODIStsp by  looking for the word "timeout" in the "MODIStsp_lpdaac_accessoires.R" and "MODIStsp_process.R" functions and see if it improves things. 

HTH, 

Lorenzo

**Comment by lbusett** [comment]
Hi, closing this now - reopen if needed !

**Comment by ChrisMwene** [comment]
Hi Lorenzo
for the past 1 week now, am also facing the same issue. in some cases downloads for a single date takes more than 2 hours to complete.

As you suggested in your comments above, this is what I get when I run MODIStsp(test = 4)

> MODIStsp(test = 4)
MODIStsp is running in test mode.
GDAL version in use: 3.0.4
[Fri Nov 27 17:13:34 2020] MODIStsp --> Starting processing
[Fri Nov 27 17:13:34 2020] Accessing http server at:  https://n5eil01u.ecs.nsidc.org/MOST/MOD10CM.006/
[Fri Nov 27 17:13:45 2020] Retrieving list of available ` Terra ` Files for Year 2015
[Fri Nov 27 17:13:49 2020] Downloading Terra Files for date: 2015_08_01 : 1 of:  1
[Fri Nov 27 17:14:36 2020] [Fri Nov 27 17:14:36 2020] 1 files for date: 2015.08.01 were successfully downloaded!
[Fri Nov 27 17:14:37 2020] Processing and Reprojecting Terra SN_COV_MNT files for date: 2015_08_01
[Fri Nov 27 17:14:46 2020] Retrieving list of available ` Terra ` Files for Year 2016
[Fri Nov 27 17:14:48 2020] Downloading Terra Files for date: 2016_08_01 : 1 of:  1
[Fri Nov 27 17:15:39 2020] [Fri Nov 27 17:15:39 2020] 1 files for date: 2016.08.01 were successfully downloaded!
[Fri Nov 27 17:15:39 2020] Processing and Reprojecting Terra SN_COV_MNT files for date: 2016_08_01
[Fri Nov 27 17:15:43 2020] Accessing http server at:  https://n5eil01u.ecs.nsidc.org/MOSA/MYD10CM.006/
[Fri Nov 27 17:15:46 2020] Retrieving list of available ` Aqua ` Files for Year 2015
[Fri Nov 27 17:15:48 2020] Downloading Aqua Files for date: 2015_08_01 : 1 of:  1
[Fri Nov 27 17:16:56 2020] [Fri Nov 27 17:16:56 2020] 1 files for date: 2015.08.01 were successfully downloaded!
[Fri Nov 27 17:16:56 2020] Processing and Reprojecting Aqua SN_COV_MNT files for date: 2015_08_01
[Fri Nov 27 17:17:02 2020] Retrieving list of available ` Aqua ` Files for Year 2016
[Fri Nov 27 17:17:04 2020] Downloading Aqua Files for date: 2016_08_01 : 1 of:  1
[Fri Nov 27 17:18:14 2020] [Fri Nov 27 17:18:14 2020] 1 files for date: 2016.08.01 were successfully downloaded!
[Fri Nov 27 17:18:14 2020] Processing and Reprojecting Aqua SN_COV_MNT files for date: 2016_08_01
[Fri Nov 27 17:18:17 2020] Creating Virtual Files and R time series for layer SN_COV_MNT
[Fri Nov 27 17:18:17 2020] Creating Virtual Files and R time series for layer SN_COV_MNT
[Fri Nov 27 17:18:18 2020] Creating Virtual Files and R time series for layer SN_COV_MNT
[Fri Nov 27 17:18:18 2020] Total Processing Time: 4.73123201529185
[Fri Nov 27 17:18:18 2020] MODIStsp processed files are in: `C:\Users\CHRIST~1\AppData\Local\Temp\RtmpGQjZRp/MODIStsp`
[Fri Nov 27 17:18:18 2020] Original downloaded MODIS HDF files are in: `C:\Users\CHRIST~1\AppData\Local\Temp\RtmpGQjZRp/MODIStsp/HDFs`
[Fri Nov 27 17:18:18 2020] Processing options saved to: `C:\Users\CHRIST~1\AppData\Local\Temp\RtmpGQjZRp/MODIStsp/MODIStsp_2020-11-27.json`
[1] "DONE"

and MODIStsp(test = 6)

> MODIStsp(test = 6)
MODIStsp is running in test mode.
GDAL version in use: 3.0.4
[Fri Nov 27 17:35:29 2020] MODIStsp --> Starting processing
[Fri Nov 27 17:35:29 2020] Accessing http server at:  https://e4ftl01.cr.usgs.gov/MOTA/MCD15A2H.006/
[Fri Nov 27 17:35:34 2020] Retrieving list of available ` Combined ` Files for Year 2016
[Fri Nov 27 17:35:51 2020] Downloading Terra Files for date: 2016_07_19 : 1 of:  2
[Fri Nov 27 17:50:10 2020] Downloading Terra Files for date: 2016_07_19 : 2 of:  2
[Fri Nov 27 17:54:03 2020] [Fri Nov 27 17:54:03 2020] 2 files for date: 2016.07.19 were successfully downloaded!
[Fri Nov 27 17:54:03 2020] Processing and Reprojecting Terra Lai files for date: 2016_07_19
[Fri Nov 27 17:54:23 2020] Downloading Terra Files for date: 2016_07_27 : 1 of:  2
[Fri Nov 27 18:07:54 2020] Downloading Terra Files for date: 2016_07_27 : 2 of:  2
[Fri Nov 27 18:10:10 2020] [Fri Nov 27 18:10:10 2020] 2 files for date: 2016.07.27 were successfully downloaded!
[Fri Nov 27 18:10:10 2020] Processing and Reprojecting Terra Lai files for date: 2016_07_27
[Fri Nov 27 18:10:13 2020] Creating Virtual Files and R time series for layer Lai
[Fri Nov 27 18:10:13 2020] Total Processing Time: 34.7278120001157
[Fri Nov 27 18:10:13 2020] MODIStsp processed files are in: `C:\Users\CHRIST~1\AppData\Local\Temp\RtmpGQjZRp/MODIStsp`
[Fri Nov 27 18:10:13 2020] Original downloaded MODIS HDF files are in: `C:\Users\CHRIST~1\AppData\Local\Temp\RtmpGQjZRp/MODIStsp/HDFs`
[Fri Nov 27 18:10:13 2020] Processing options saved to: `C:\Users\CHRIST~1\AppData\Local\Temp\RtmpGQjZRp/MODIStsp/MODIStsp_2020-11-27.json`
[1] "DONE"


these are my options
[options.json.txt](https://github.com/ropensci/MODIStsp/files/5608827/options.json.txt)

Please help.
